const fs = require('fs');
let code = fs.readFileSync('client/src/context/LanguageContext.jsx', 'utf8');

const regex = /deleteTestMsg:\s*'Бұл тестті жоюды қалайсыз ба\? Барлық нәтижелер де жойылады\.',\s*\}\s*\};/;

const replacement = `    deleteTestMsg: 'Бұл тестті жоюды қалайсыз ба? Барлық нәтижелер де жойылады.',
  },
  es: {
    landingBadge: 'La forma más fácil de evaluar conocimientos',
    landingHeroTitle: 'Evalúa con confianza,',
    landingHeroSubtitle: 'impulsado por IA',
    landingHeroDesc: 'UniTest es una plataforma integral para educadores para crear pruebas, monitorear a los estudiantes y analizar resultados.',
    landingStartBtn: 'Comenzar gratis',
    landingLoginBtn: 'Iniciar sesión',
    landingFeaturesHeader: 'Todo lo que necesitas para tener éxito',
    landingFeaturesSubHeader: 'Herramientas potentes diseñadas para educadores modernos e instituciones.',
    landingFeatureAIGenTitle: 'Generación por IA',
    landingFeatureAIGenDesc: 'Genera preguntas a partir de texto o documentos al instante usando IA.',
    landingFeatureLevelsTitle: 'ADN de Dificultad',
    landingFeatureLevelsDesc: 'Sistema dinámico de 5 niveles de dificultad para una evaluación precisa.',
    landingFeatureAnalyticsTitle: 'Análisis Profundo',
    landingFeatureAnalyticsDesc: 'Sigue el rendimiento con análisis en tiempo real e informes detallados.',
    landingFeatureSecurityTitle: 'Anti-Trampas',
    landingFeatureSecurityDesc: 'Bloqueo del navegador, rastreo de pestañas para pruebas honestas.',
    landingStepsHeader: 'Cómo funciona',
    landingStepsSubHeader: 'Crea tu primera prueba y obtén resultados en minutos.',
    landingStep1Title: 'Crear',
    landingStep1Desc: 'Escribe o genera preguntas en segundos.',
    landingStep2Title: 'Compartir',
    landingStep2Desc: 'Envía un breve enlace a tus estudiantes.',
    landingStep3Title: 'Analizar',
    landingStep3Desc: 'Revisión automática.',
    landingCtaHeader: '¿Listo para transformar la educación?',
    landingCtaDesc: 'Únete a miles de educadores.',
    landingCtaBtn: 'Crear cuenta gratis',
    home: 'Inicio',
    myTests: 'Mis Pruebas',
    results: 'Resultados',
    questionBank: 'Banco de Preguntas',
    groups: 'Grupos',
    createTest: 'Crear Prueba',
    profile: 'Perfil',
    admin: 'Admin',
    logout: 'Salir',
    teacher: 'Profesor',
    student: 'Estudiante',
    adminRole: 'Admin',
    lightTheme: 'Claro',
    darkTheme: 'Oscuro',
    welcome: 'Bienvenido',
    dashboardSubtitle: 'Sigue tu progreso',
    searchTests: 'Buscar...',
    newest: 'Nuevos',
    popular: 'Populares',
    rating: 'Nota',
    noTests: 'No hay pruebas',
    createFirst: 'Crea tu prueba',
    publicTest: 'Público',
    privateTest: 'Privado',
    questions: 'preguntas',
    noDescription: 'Sin descripción',
    deleteTest: 'Eliminar',
    deleteTestConfirm: '¿Eliminar prueba?',
    delete: 'Borrar',
    edit: 'Editar',
    copyLink: 'Copiar',
    linkCopied: '¡Copiado!',
    leaderboard: 'Ranking',
    totalParticipants: 'Total',
    emptyLeaderboard: 'Vacío',
    noOneCompleted: 'Nadie ha completado esto',
    error: 'Error',
    toHome: 'Inicio',
    login: 'Entrar',
    register: 'Registrarse',
    email: 'Email',
    password: 'Password',
    firstName: 'Nombre',
    lastName: 'Apellido',
    middleName: 'Segundo',
    noAccount: '¿No cuenta?',
    haveAccount: '¿Ya estás?',
    loginBtn: 'Entrar',
    registerBtn: 'Registrarse',
    profileTitle: 'Perfil',
    editProfile: 'Editar',
    changePassword: 'Password',
    currentPassword: 'Actual',
    newPassword: 'Nueva',
    save: 'Guardar',
    cancel: 'Cancelar',
    language: 'Idioma',
    uploadAvatar: 'Avatar',
    warnings: 'Avisos',
    memberSince: 'Desde',
    loading: '...',
    errorLoading: 'Error',
    back: 'Atrás',
    startTest: 'Inicia',
    submitTest: 'Enviar',
    nextQuestion: 'Siguiente',
    prevQuestion: 'Atrás',
    timeLeft: 'Tiempo',
    question: 'Preg',
    of: 'de',
    comments: 'Comments',
    addComment: 'Añadir',
    writeComment: 'Escribe...',
    send: 'Enviá',
    reply: 'Resp',
    commentsDisabled: 'Off',
    deleteComment: 'Borrar',
    adminPanel: 'Admin',
    users: 'U',
    tests: 'T',
    statistics: 'S',
    ban: 'B',
    unban: 'U',
    warn: 'W',
    banned: 'Bloq',
    role: 'Rol',
    search: 'Busc',
    totalUsers: 'Total Usrs',
    totalTests: 'Total Test',
    totalResults: 'Total Res',
    bannedUsers: 'Baneado',
    changeRole: 'Rol',
    banUser: 'Ban',
    banReason: 'Motivo',
    warnMessage: 'Mensaj',
    recentUsers: 'Rec',
    recentTests: 'Rec T',
    testResults: 'Resultados',
    score: 'Punt',
    passed: 'OK',
    failed: 'F',
    viewResults: 'Ver',
    notifications: 'Notis',
    noNotifications: 'Sin notis',
    markAllRead: 'Leido',
    report: 'Report',
    reportReason: 'R',
    reportSent: 'Enviado',
    reportTest: 'T',
    reportComment: 'C',
    reportUser: 'U',
    editComment: 'Edit',
    cancelEditConfirm: 'Can?',
    edited: 'ed',
    testCreator: 'Creador',
    userProfile: 'Perfil',
    testsCreated: 'Creados',
    testsTaken: 'Tomados',
    exportCSV: 'CSV',
    exportJSON: 'JSON',
    exportPDF: 'PDF',
    draftFound: 'Borrador',
    restoreDraft: 'Restore?',
    restore: 'Sí',
    discard: 'No',
    instantFeedback: 'IFeedback',
    instantFeedbackDesc: 'Al instante',
    correct: 'C',
    incorrect: 'I',
    checkAnswer: 'Chk',
    explanation: 'E',
    addPassage: 'Añad',
    hidePassage: 'Hid',
    passage: 'T',
    passagePlaceholder: '...',
    passageLabel: 'TXT',
    singleChoice: 'Simple',
    multipleChoice: 'Múltiple',
    trueFalse: 'V/F',
    essay: 'E',
    matching: 'Emp',
    fillBlank: 'Llena',
    optTrue: 'Verdad',
    optFalse: 'Falso',
    optNotSure: 'NS',
    minOneQuestion: 'Min 1',
    enterTestTitle: 'Titulo',
    fillAllQuestions: 'Pregs',
    testUpdated: 'UP',
    testCreated: 'CR',
    errorSaving: 'Err',
    mediaUploaded: 'MU',
    errorUploadMedia: 'Err M',
    importedQuestions: 'I',
    cannotParseQuestions: 'CP',
    errorReadingFile: 'ER',
    errorLoadingBank: 'EL',
    addedFromBank: 'AB',
    savedToBank: 'SB',
    errorSavingToBank: 'ES',
    deleteQuestion: 'DQ',
    deleteQuestionConfirm: 'DQC?',
    navigation: 'N',
    questionsCount: 'Q',
    pointsCount: 'P',
    fromQuestionBank: 'F',
    importCSV: 'IM',
    saveToBank: 'SB',
    aiGenerate: 'Generar IA',
    aiGenerateDesc: 'Generador',
    aiTextInput: 'Text',
    aiTextPlaceholder: 'Text...',
    aiImageInput: 'Img',
    aiUploadImage: 'Upp',
    aiQuestionCount: 'Cnt',
    aiQuestionTypes: 'Typ',
    aiGenerateBtn: 'Btn',
    aiGenerating: 'Load...',
    aiPoweredBy: 'AI',
    aiProvideContent: 'Prv',
    aiNoQuestions: 'Nul',
    aiFileTooLarge: 'Bg',
    aiQuestionsAdded: 'Add',
    editTest: 'Edit',
    settings: 'Set',
    update: 'Upd',
    testSettings: 'Ts Set',
    timeLimitMin: 'Tm',
    maxAttempts: 'Atmp',
    maxViolations: 'Viol',
    isPublic: 'Pub',
    shuffleQuestions: 'Shufl pregs',
    shuffleOptions: 'Shufl opts',
    showResults: 'Show Res',
    blockTabSwitch: 'Blok Tab',
    blockCopyPaste: 'Blok Cp',
    blockScreenshot: 'Blok Scr',
    testTitlePlaceholder: '...',
    testDescPlaceholder: '...',
    newQuestion: '...',
    questionTextPlaceholder: '...',
    addMedia: '...',
    optionPlaceholder: '...',
    addOption: '...',
    essayHint: '...',
    correctAnswer: '...',
    enterCorrectAnswer: '...',
    element: 'E',
    pair: 'P',
    addPair: 'A',
    explanationPlaceholder: '...',
    addQuestion: '...',
    updateTest: '...',
    saveTest: '...',
    importFromCSV: '...',
    clickToSelectFile: '...',
    questionBankTitle: '...',
    bankEmpty: '...',
    selectQuestions: '...',
    addSelected: '...',
    close: 'X',
    points: 'pt',
    savingDraft: 'S...',
    draftSaved: 'SD',
    noLimitPlaceholder: '0',
    startDate: 'S',
    endDate: 'E',
    questionPoolSize: 'Q',
    poolSizeHint: '0',
    inactivityTimeout: 'I',
    inactivityHint: '0',
    practiceMode: 'P',
    practiceModeDesc: 'P',
    practiceModeLabel: 'P',
    partialCredit: 'Pc',
    partialCreditDesc: 'Pc',
    changeTicket: 'C',
    ticketHintPublic: 'C',
    aiHistory: 'A',
    aiNoHistory: 'A',
    clearAll: 'Clear',
    exportJSON: 'EJ',
    importJSON: 'IJ',
    exportSuccess: 'ES',
    importSuccess: 'IS',
    importError: 'IE',
    preview: 'P',
    previewMode: 'P',
    inactivityWarning: 'W',
    inactivityCountdownMsg: 'W',
    imHere: 'H',
    category: 'C',
    allCategories: 'C',
    ticketN: '#',
    chooseTicket: 'T',
    ticketReady: 'T',
    claimingTicket: 'T',
    ticketHint: 'T',
    variantsEnabled: 'V',
    variantCount: 'V',
    variantsHint: 'V',
    matchingHint: 'M',
    elements: 'E',
    pairs: 'P',
    yourPairs: 'Y',
    violationLimitExceeded: 'V',
    timeUp: 'T',
    testNotFound: 'T',
    enterYourName: 'E',
    errorCheckingAnswer: 'E',
    errorSubmitting: 'E',
    point: 'P',
    multipleAnswersHint: 'M',
    checking: 'C',
    writeYourAnswer: 'W',
    essayCheckedByTeacher: 'E',
    enterAnswer: 'E',
    correctAnswerIs: 'C',
    explanationLabel: 'E',
    correctBanner: 'C',
    incorrectBanner: 'I',
    outOfPoints: 'O',
    finishTest: 'F',
    finishTestTitle: 'F',
    finishTestMessage: 'F',
    finishBtn: 'F',
    continueTest: 'C',
    startTestBtn: 'S',
    yourName: 'Y',
    enterFullName: 'E',
    attempts: 'A',
    allAttemptsUsed: 'A',
    testRules: 'T',
    ruleNoLeave: 'R',
    ruleViolationsTracked: 'R',
    ruleMaxViolations: 'R',
    modeInstantFeedback: 'M',
    instantFeedbackInfo: 'I',
    answered: 'A',
    selectOption: 'S',
    navigation: 'N',
    violation: 'V',
    violationCount: 'V',
    understood: 'U',
    next: 'Sig',
    prev: 'Ant',
    questionTypes: 'Tipos',
    rateTest: 'Votar',
    yourRating: 'Tu voto',
    clickToRate: 'Votar',
    loginToRate: 'Log',
    ratingUpdated: 'Upd',
    thanksForRating: 'Thx',
    tabSwitchBlocked: 'Blckd',
    allAttemptsUsedFull: 'Atps used',
    viewAll: 'All',
    min: 'm',
    noCorrectAnswer: 'No CA',
    emptyOptions: 'EO',
    errorLoadingTests: 'ELT',
    testDeleted: 'TD',
    errorDeleting: 'ED',
    deleteTestTitle: 'DT',
    deleteTestMsg: 'DTM'
  }
};`;

if (code.match(regex)) {
  code = code.replace(regex, replacement);
  fs.writeFileSync('client/src/context/LanguageContext.jsx', code, 'utf8');
} else {
  console.log("Could not find match to inject 'es'.");
}
