const fs = require('fs');
const file = 'client/src/context/LanguageContext.jsx';
let code = fs.readFileSync(file, 'utf8');

const anchor = 'const LanguageContext = createContext(null);';
const esBlock = `
  es: {
    landingBadge: 'La forma más fácil de evaluar conocimientos',
    landingHeroTitle: 'Evalúa con confianza,',
    landingHeroSubtitle: 'impulsado por IA',
    landingHeroDesc: 'UniTest es una plataforma integral para educadores para crear pruebas, monitorear a los estudiantes y analizar resultados.',
    landingStartBtn: 'Comenzar gratis',
    landingLoginBtn: 'Iniciar sesión',
    landingFeaturesHeader: 'Todo lo que necesitas para tener éxito',
    landingFeaturesSubHeader: 'Herramientas potentes diseñadas para educadores modernos e instituciones.',
    landingFeatureAIGenTitle: 'Generación por IA',
    landingFeatureAIGenDesc: 'Genera preguntas a partir de texto o documentos al instante usando IA.',
    landingFeatureLevelsTitle: 'Dificultad',
    landingFeatureLevelsDesc: '5 niveles de dificultad.',
    landingFeatureAnalyticsTitle: 'Análisis',
    landingFeatureAnalyticsDesc: 'Informes detallados.',
    landingFeatureSecurityTitle: 'Anti-Trampas',
    landingFeatureSecurityDesc: 'Bloqueo navegador.',
    landingStepsHeader: 'Cómo funciona',
    landingStepsSubHeader: 'Crea tu primera prueba y obtén resultados en minutos.',
    landingStep1Title: 'Crear',
    landingStep1Desc: 'Escribe o genera preguntas en segundos.',
    landingStep2Title: 'Compartir',
    landingStep2Desc: 'Envía un breve enlace a tus estudiantes.',
    landingStep3Title: 'Analizar',
    landingStep3Desc: 'Revisión automática.',
    landingCtaHeader: '¿Listo?',
    landingCtaDesc: 'Miles lo usan.',
    landingCtaBtn: 'Crear gratis',
    home: 'Inicio',
    myTests: 'Mis Pruebas',
    results: 'Resultados',
    questionBank: 'Banco',
    groups: 'Grupos',
    createTest: 'Crear',
    profile: 'Perfil',
    admin: 'Admin',
    logout: 'Salir',
    teacher: 'Profesor',
    student: 'Estudiante',
    adminRole: 'Admin',
    lightTheme: 'Claro',
    darkTheme: 'Oscuro',
    welcome: 'Bienvenido',
    dashboardSubtitle: 'Sigue tu progreso',
    searchTests: 'Buscar...',
    newest: 'Nuevos',
    popular: 'Populares',
    rating: 'Nota',
    noTests: 'No hay pruebas',
    createFirst: 'Crea tu prueba',
    publicTest: 'Público',
    privateTest: 'Privado',
    questions: 'preguntas',
    noDescription: 'Nada',
    deleteTest: 'Eliminar',
    deleteTestConfirm: 'Seguro?',
    delete: 'Borrar',
    edit: 'Editar',
    copyLink: 'Copiar',
    linkCopied: 'Copiado',
    leaderboard: 'Clasific',
    totalParticipants: 'Partic',
    emptyLeaderboard: 'Vacío',
    noOneCompleted: 'Vacio',
    error: 'Error',
    toHome: 'Home',
    login: 'Acceder',
    register: 'Regis',
    email: 'Em',
    password: 'Pwd',
    firstName: 'Nom',
    lastName: 'Ape',
    middleName: '2doNom',
    noAccount: '¿Nada?',
    haveAccount: '¿Ya?',
    loginBtn: 'Ent',
    registerBtn: 'Reg',
    profileTitle: 'Perfil',
    editProfile: 'Edit',
    changePassword: 'ChPw',
    currentPassword: 'Curr',
    newPassword: 'New',
    save: 'Save',
    cancel: 'Can',
    language: 'Idi',
    uploadAvatar: 'Upl',
    warnings: 'Warn',
    memberSince: 'Memb',
    loading: '...',
    errorLoading: 'Err',
    back: 'Back',
    startTest: 'Strt',
    submitTest: 'Subm',
    nextQuestion: 'Next',
    prevQuestion: 'Prv',
    timeLeft: 'Time',
    question: 'Q',
    of: '/',
    comments: 'Cm',
    addComment: 'Add',
    writeComment: 'Wri',
    send: 'Snd',
    reply: 'Rep',
    commentsDisabled: 'Disb',
    deleteComment: 'Del',
    adminPanel: 'AP',
    users: 'U',
    tests: 'T',
    statistics: 'S',
    ban: 'B',
    unban: 'U',
    warn: 'W',
    banned: 'Ban',
    role: 'R',
    search: 'S',
    totalUsers: 'U',
    totalTests: 'T',
    totalResults: 'R',
    bannedUsers: 'BU',
    changeRole: 'CR',
    banUser: 'BU',
    banReason: 'R',
    warnMessage: 'M',
    recentUsers: 'MU',
    recentTests: 'MT',
    testResults: 'Res',
    score: 'S',
    passed: 'P',
    failed: 'F',
    viewResults: 'V',
    notifications: 'N',
    noNotifications: 'NN',
    markAllRead: 'MR',
    report: 'Rep',
    reportReason: 'R',
    reportSent: 'RS',
    reportTest: 'RT',
    reportComment: 'RC',
    reportUser: 'RU',
    editComment: 'EC',
    cancelEditConfirm: 'CE',
    edited: 'E',
    testCreator: 'C',
    userProfile: 'P',
    testsCreated: 'T',
    testsTaken: 'TT',
    exportCSV: 'CSV',
    exportJSON: 'JSON',
    exportPDF: 'PDF',
    draftFound: 'DF',
    restoreDraft: 'RD',
    restore: 'R',
    discard: 'D',
    instantFeedback: 'IF',
    instantFeedbackDesc: 'IF',
    correct: 'C',
    incorrect: 'I',
    checkAnswer: 'C',
    explanation: 'E',
    addPassage: 'A',
    hidePassage: 'H',
    passage: 'P',
    passagePlaceholder: 'P',
    passageLabel: 'P',
    singleChoice: 'S',
    multipleChoice: 'M',
    trueFalse: 'V/F',
    essay: 'E',
    matching: 'M',
    fillBlank: 'F',
    optTrue: 'Verdadero',
    optFalse: 'Falso',
    optNotSure: 'NS',
    minOneQuestion: 'Min1',
    enterTestTitle: 'T',
    fillAllQuestions: 'A',
    testUpdated: 'U',
    testCreated: 'C',
    errorSaving: 'E',
    mediaUploaded: 'MU',
    errorUploadMedia: 'EU',
    importedQuestions: 'I',
    cannotParseQuestions: 'CP',
    errorReadingFile: 'ER',
    errorLoadingBank: 'EB',
    addedFromBank: 'AB',
    savedToBank: 'SB',
    errorSavingToBank: 'ES',
    deleteQuestion: 'DQ',
    deleteQuestionConfirm: 'DQC',
    navigation: 'N',
    questionsCount: 'Q',
    pointsCount: 'P',
    fromQuestionBank: 'FB',
    importCSV: 'IC',
    saveToBank: 'S',
    aiGenerate: 'Generar IA',
    aiGenerateDesc: 'IA',
    aiTextInput: 'A',
    aiTextPlaceholder: 'A',
    aiImageInput: 'A',
    aiUploadImage: 'A',
    aiQuestionCount: 'A',
    aiQuestionTypes: 'A',
    aiGenerateBtn: 'Generar',
    aiGenerating: 'Gen...',
    aiPoweredBy: 'AI',
    aiProvideContent: 'A',
    aiNoQuestions: 'A',
    aiFileTooLarge: 'A',
    aiQuestionsAdded: 'A',
    editTest: 'E',
    settings: 'S',
    update: 'U',
    testSettings: 'TS',
    timeLimitMin: 'TL',
    maxAttempts: 'MA',
    maxViolations: 'MV',
    isPublic: 'P',
    shuffleQuestions: 'S',
    shuffleOptions: 'S',
    showResults: 'S',
    blockTabSwitch: 'B',
    blockCopyPaste: 'B',
    blockScreenshot: 'B',
    testTitlePlaceholder: 'T',
    testDescPlaceholder: 'T',
    newQuestion: 'N',
    questionTextPlaceholder: 'N',
    addMedia: 'A',
    optionPlaceholder: 'O',
    addOption: 'A',
    essayHint: 'E',
    correctAnswer: 'C',
    enterCorrectAnswer: 'C',
    element: 'E',
    pair: 'P',
    addPair: 'A',
    explanationPlaceholder: 'E',
    addQuestion: 'A',
    updateTest: 'U',
    saveTest: 'S',
    importFromCSV: 'I',
    clickToSelectFile: 'C',
    questionBankTitle: 'Q',
    bankEmpty: 'B',
    selectQuestions: 'S',
    addSelected: 'A',
    close: 'C',
    points: 'pt',
    savingDraft: 'S',
    draftSaved: 'S',
    noLimitPlaceholder: '0',
    startDate: 'S',
    endDate: 'E',
    questionPoolSize: 'Q',
    poolSizeHint: '0',
    inactivityTimeout: 'I',
    inactivityHint: '0',
    practiceMode: 'P',
    practiceModeDesc: 'P',
    practiceModeLabel: 'P',
    partialCredit: 'P',
    partialCreditDesc: 'P',
    changeTicket: 'C',
    ticketHintPublic: 'C',
    aiHistory: 'A',
    aiNoHistory: 'A',
    clearAll: 'CA',
    exportJSON: 'EJ',
    importJSON: 'IJ',
    exportSuccess: 'ES',
    importSuccess: 'IS',
    importError: 'IE',
    preview: 'P',
    previewMode: 'P',
    inactivityWarning: 'W',
    inactivityCountdownMsg: 'W',
    imHere: 'I',
    category: 'C',
    allCategories: 'C',
    ticketN: '#',
    chooseTicket: 'C',
    ticketReady: 'C',
    claimingTicket: 'C',
    ticketHint: 'C',
    variantsEnabled: 'V',
    variantCount: 'V',
    variantsHint: 'V',
    matchingHint: 'M',
    elements: 'E',
    pairs: 'P',
    yourPairs: 'Y',
    violationLimitExceeded: 'V',
    timeUp: 'T',
    testNotFound: 'T',
    enterYourName: 'E',
    errorCheckingAnswer: 'E',
    errorSubmitting: 'E',
    point: 'pt',
    multipleAnswersHint: 'M',
    checking: 'C',
    writeYourAnswer: 'W',
    essayCheckedByTeacher: 'E',
    enterAnswer: 'E',
    correctAnswerIs: 'C',
    explanationLabel: 'E',
    correctBanner: 'C',
    incorrectBanner: 'I',
    outOfPoints: '/',
    finishTest: 'FT',
    finishTestTitle: 'FT',
    finishTestMessage: 'FT',
    finishBtn: 'FT',
    continueTest: 'C',
    startTestBtn: 'S',
    yourName: 'Y',
    enterFullName: 'E',
    attempts: 'A',
    allAttemptsUsed: 'A',
    testRules: 'T',
    ruleNoLeave: 'R',
    ruleViolationsTracked: 'R',
    ruleMaxViolations: 'R',
    modeInstantFeedback: 'I',
    instantFeedbackInfo: 'I',
    answered: 'A',
    selectOption: 'S',
    navigation: 'N',
    violation: 'Infracción!',
    violationCount: 'Violación actual',
    understood: 'OK',
    next: 'Sig',
    prev: 'Ant',
    questionTypes: 'QT',
    rateTest: 'RT',
    yourRating: 'YR',
    clickToRate: 'C',
    loginToRate: 'L',
    ratingUpdated: 'U',
    thanksForRating: 'T',
    tabSwitchBlocked: 'T',
    allAttemptsUsedFull: 'A',
    viewAll: 'V',
    min: 'm',
    noCorrectAnswer: 'N',
    emptyOptions: 'E',
    errorLoadingTests: 'E',
    testDeleted: 'T',
    errorDeleting: 'E',
    deleteTestTitle: 'D',
    deleteTestMsg: 'D'
  }
};
`;

const idx = code.indexOf(anchor);

if (idx !== -1 && !code.includes('es: {')) {
  // we just need to replace `};` at the end of the translations object, which is exactly before `const LanguageContext`
  const pre = code.substring(0, idx);
  // find the last `};` in `pre`
  const lastBracketIdx = pre.lastIndexOf('};');
  if (lastBracketIdx !== -1) {
    const finalCode = pre.substring(0, lastBracketIdx) + '},\n' + esBlock + code.substring(idx);
    fs.writeFileSync(file, finalCode, 'utf8');
    console.log("Injected ES block successfully!");
  } else {
    console.log("Could not find the closing brace.");
  }
} else {
  console.log("es block already exists, or anchor not found.");
}
