export const profileCopy = {
  en: {
    headline: 'Headline',
    bio: 'Bio',
    headlinePlaceholder: 'Short line that introduces you as a creator or learner',
    bioPlaceholder: 'Write a short public description for your profile.',
    choosePreset: 'Cover preset',
    presets: {
      aurora: 'Aurora',
      mesh: 'Mesh',
      wave: 'Wave',
      grid: 'Grid'
    },
    uploadBanner: 'Upload banner',
    replaceBanner: 'Replace banner',
    removeBanner: 'Remove banner',
    saveProfile: 'Save changes',
    profileUpdated: 'Profile updated',
    avatarUpdated: 'Avatar updated',
    bannerUpdated: 'Banner updated',
    bannerRemoved: 'Banner removed',
    level: 'Level',
    xp: 'XP',
    currentStreak: 'Current streak',
    bestStreak: 'Best streak',
    completedExams: 'Completed tests',
    completedPractice: 'Practice runs',
    perfectScores: 'Perfect scores',
    badges: 'Badges',
    noBadges: 'Badges will appear after completed tests.',
    followers: 'Followers',
    following: 'Following',
    openFollowers: 'Open followers',
    openFollowing: 'Open following',
    follow: 'Follow',
    unfollow: 'Unfollow',
    creatorStats: 'Creator stats',
    publicRating: 'Public rating',
    publicPlays: 'Public plays',
    publishedTests: 'Published tests',
    publicTests: 'Public tests',
    viewAllPublished: 'View all',
    noPublicTests: 'No public tests yet.',
    loadingProfiles: 'Loading list...',
    noFollowers: 'No followers yet.',
    noFollowing: 'No subscriptions yet.',
    profileLoadError: 'Failed to load profile',
    saveError: 'Failed to save profile',
    followError: 'Failed to update follow status',
    joined: 'Joined',
    uniqueId: 'ID',
    about: 'About',
    overview: 'Overview',
    security: 'Security',
    comments: 'Comments',
    publicProgress: 'Public progress',
    creatorPortfolio: 'Creator portfolio',
    tabOverview: 'Overview',
    tabAccount: 'Profile',
    tabAppearance: 'Appearance',
    tabSecurity: 'Security',
    tabActivity: 'Activity',
    tabOverviewDesc: 'Your snapshot and creator stats',
    tabAccountDesc: 'Identity, username, bio',
    tabAppearanceDesc: 'Cover, theme and language',
    tabSecurityDesc: 'Password and account safety',
    tabActivityDesc: 'Warnings, comments and history',
    overviewHeadline: 'Welcome back',
    overviewSubtitle: 'A quick look at your progress and creator work.',
    accountHeadline: 'Account details',
    accountSubtitle: 'Public information shown across the platform.',
    appearanceHeadline: 'Look and feel',
    appearanceSubtitle: 'Customize how your profile looks to others.',
    securityHeadline: 'Security',
    securitySubtitle: 'Keep your account safe.',
    activityHeadline: 'Activity history',
    activitySubtitle: 'Warnings, comments and achievements.',
    seeAll: 'See all',
    noActivity: 'No activity yet.',
    copyId: 'Copy ID',
    idCopied: 'ID copied',
    tabPublicOverview: 'Overview',
    tabPublicTests: 'Tests',
    tabPublicAchievements: 'Achievements',
    tabPublicOverviewDesc: 'Snapshot and creator stats',
    tabPublicTestsDesc: 'Published public tests',
    tabPublicAchievementsDesc: 'Unlocked badges and milestones',
    publicOverviewSubtitle: 'Public profile at a glance.',
    publicTestsSubtitle: 'All public tests by this creator.',
    publicAchievementsSubtitle: 'Badges unlocked on the platform.'
  },
  ru: {
    headline: 'Заголовок профиля',
    bio: 'О себе',
    headlinePlaceholder: 'Коротко опиши себя как автора или ученика',
    bioPlaceholder: 'Добавь публичное описание профиля.',
    choosePreset: 'Пресет обложки',
    presets: {
      aurora: 'Аврора',
      mesh: 'Сетка',
      wave: 'Волна',
      grid: 'Грид'
    },
    uploadBanner: 'Загрузить баннер',
    replaceBanner: 'Заменить баннер',
    removeBanner: 'Удалить баннер',
    saveProfile: 'Сохранить изменения',
    profileUpdated: 'Профиль обновлён',
    avatarUpdated: 'Аватар обновлён',
    bannerUpdated: 'Баннер обновлён',
    bannerRemoved: 'Баннер удалён',
    level: 'Уровень',
    xp: 'XP',
    currentStreak: 'Текущая серия',
    bestStreak: 'Лучшая серия',
    completedExams: 'Завершённые тесты',
    completedPractice: 'Тренировки',
    perfectScores: 'Идеальные результаты',
    badges: 'Достижения',
    noBadges: 'Достижения появятся после завершённых тестов.',
    followers: 'Подписчики',
    following: 'Подписки',
    openFollowers: 'Открыть подписчиков',
    openFollowing: 'Открыть подписки',
    follow: 'Подписаться',
    unfollow: 'Отписаться',
    creatorStats: 'Статистика автора',
    publicRating: 'Рейтинг публичных тестов',
    publicPlays: 'Публичные прохождения',
    publishedTests: 'Опубликованные тесты',
    publicTests: 'Публичные тесты',
    viewAllPublished: 'Смотреть все',
    noPublicTests: 'Публичных тестов пока нет.',
    loadingProfiles: 'Загрузка списка...',
    noFollowers: 'Подписчиков пока нет.',
    noFollowing: 'Подписок пока нет.',
    profileLoadError: 'Не удалось загрузить профиль',
    saveError: 'Не удалось сохранить профиль',
    followError: 'Не удалось обновить подписку',
    joined: 'На платформе с',
    uniqueId: 'ID',
    about: 'О профиле',
    overview: 'Обзор',
    security: 'Безопасность',
    comments: 'Комментарии',
    publicProgress: 'Публичный прогресс',
    creatorPortfolio: 'Портфолио автора',
    tabOverview: 'Обзор',
    tabAccount: 'Профиль',
    tabAppearance: 'Внешний вид',
    tabSecurity: 'Безопасность',
    tabActivity: 'Активность',
    tabOverviewDesc: 'Сводка и статистика автора',
    tabAccountDesc: 'Имя, username, описание',
    tabAppearanceDesc: 'Обложка, тема и язык',
    tabSecurityDesc: 'Пароль и безопасность аккаунта',
    tabActivityDesc: 'Предупреждения, комментарии и достижения',
    overviewHeadline: 'С возвращением',
    overviewSubtitle: 'Краткий взгляд на твой прогресс и работу как автора.',
    accountHeadline: 'Данные профиля',
    accountSubtitle: 'Публичная информация, которую видят другие пользователи.',
    appearanceHeadline: 'Внешний вид',
    appearanceSubtitle: 'Настрой, как твой профиль выглядит для других.',
    securityHeadline: 'Безопасность',
    securitySubtitle: 'Держи аккаунт в безопасности.',
    activityHeadline: 'История активности',
    activitySubtitle: 'Предупреждения, комментарии и достижения.',
    seeAll: 'Смотреть всё',
    noActivity: 'Активности пока нет.',
    copyId: 'Скопировать ID',
    idCopied: 'ID скопирован',
    tabPublicOverview: 'Обзор',
    tabPublicTests: 'Тесты',
    tabPublicAchievements: 'Достижения',
    tabPublicOverviewDesc: 'Сводка и статистика автора',
    tabPublicTestsDesc: 'Опубликованные тесты',
    tabPublicAchievementsDesc: 'Полученные бейджи и вехи',
    publicOverviewSubtitle: 'Краткий взгляд на публичный профиль.',
    publicTestsSubtitle: 'Все публичные тесты этого автора.',
    publicAchievementsSubtitle: 'Бейджи, полученные на платформе.'
  },
  kz: {
    headline: 'Профиль тақырыбы',
    bio: 'Өзің туралы',
    headlinePlaceholder: 'Өзіңді автор немесе оқушы ретінде қысқаша таныстыр',
    bioPlaceholder: 'Профильге қысқа ашық сипаттама жаз.',
    choosePreset: 'Мұқаба пресеті',
    presets: {
      aurora: 'Аврора',
      mesh: 'Тор',
      wave: 'Толқын',
      grid: 'Грид'
    },
    uploadBanner: 'Баннер жүктеу',
    replaceBanner: 'Баннерді ауыстыру',
    removeBanner: 'Баннерді өшіру',
    saveProfile: 'Өзгерістерді сақтау',
    profileUpdated: 'Профиль жаңартылды',
    avatarUpdated: 'Аватар жаңартылды',
    bannerUpdated: 'Баннер жаңартылды',
    bannerRemoved: 'Баннер өшірілді',
    level: 'Деңгей',
    xp: 'XP',
    currentStreak: 'Қазіргі серия',
    bestStreak: 'Ең үздік серия',
    completedExams: 'Аяқталған тесттер',
    completedPractice: 'Жаттығулар',
    perfectScores: 'Мінсіз нәтижелер',
    badges: 'Жетістіктер',
    noBadges: 'Жетістіктер тесттерді аяқтағаннан кейін шығады.',
    followers: 'Жазылушылар',
    following: 'Жазылымдар',
    openFollowers: 'Жазылушыларды ашу',
    openFollowing: 'Жазылымдарды ашу',
    follow: 'Жазылу',
    unfollow: 'Жазылымнан шығу',
    creatorStats: 'Автор статистикасы',
    publicRating: 'Қоғамдық тест рейтингі',
    publicPlays: 'Қоғамдық өтулер',
    publishedTests: 'Жарияланған тесттер',
    publicTests: 'Қоғамдық тесттер',
    viewAllPublished: 'Барлығын көру',
    noPublicTests: 'Қоғамдық тесттер әлі жоқ.',
    loadingProfiles: 'Тізім жүктелуде...',
    noFollowers: 'Әлі жазылушылар жоқ.',
    noFollowing: 'Әлі жазылымдар жоқ.',
    profileLoadError: 'Профильді жүктеу мүмкін болмады',
    saveError: 'Профильді сақтау мүмкін болмады',
    followError: 'Жазылым күйін жаңарту мүмкін болмады',
    joined: 'Қосылған күні',
    uniqueId: 'ID',
    about: 'Профиль туралы',
    overview: 'Шолу',
    security: 'Қауіпсіздік',
    comments: 'Пікірлер',
    publicProgress: 'Ашық прогресс',
    creatorPortfolio: 'Автор портфолиосы',
    tabOverview: 'Шолу',
    tabAccount: 'Профиль',
    tabAppearance: 'Сыртқы көрініс',
    tabSecurity: 'Қауіпсіздік',
    tabActivity: 'Белсенділік',
    tabOverviewDesc: 'Қысқаша шолу және автор статистикасы',
    tabAccountDesc: 'Аты, username, сипаттама',
    tabAppearanceDesc: 'Мұқаба, тақырып және тіл',
    tabSecurityDesc: 'Құпиясөз және аккаунт қауіпсіздігі',
    tabActivityDesc: 'Ескертулер, пікірлер және жетістіктер',
    overviewHeadline: 'Қайта келгенің құтты болсын',
    overviewSubtitle: 'Прогрессің мен автор жұмысыңа қысқаша шолу.',
    accountHeadline: 'Профиль деректері',
    accountSubtitle: 'Платформада басқаларға көрінетін ашық ақпарат.',
    appearanceHeadline: 'Сыртқы көрініс',
    appearanceSubtitle: 'Профиліңнің басқаларға қалай көрінетінін баптап ал.',
    securityHeadline: 'Қауіпсіздік',
    securitySubtitle: 'Аккаунтыңды қауіпсіз ұста.',
    activityHeadline: 'Белсенділік тарихы',
    activitySubtitle: 'Ескертулер, пікірлер және жетістіктер.',
    seeAll: 'Барлығын көру',
    noActivity: 'Әзірге белсенділік жоқ.',
    copyId: 'ID көшіру',
    idCopied: 'ID көшірілді',
    tabPublicOverview: 'Шолу',
    tabPublicTests: 'Тесттер',
    tabPublicAchievements: 'Жетістіктер',
    tabPublicOverviewDesc: 'Қысқаша шолу және автор статистикасы',
    tabPublicTestsDesc: 'Жарияланған тесттер',
    tabPublicAchievementsDesc: 'Алынған бейджтер мен жетістіктер',
    publicOverviewSubtitle: 'Ашық профильге қысқаша шолу.',
    publicTestsSubtitle: 'Бұл автордың барлық ашық тесттері.',
    publicAchievementsSubtitle: 'Платформада алынған бейджтер.'
  },
  es: {
    headline: 'Título del perfil',
    bio: 'Biografía',
    headlinePlaceholder: 'Una línea corta sobre ti como creador o estudiante',
    bioPlaceholder: 'Escribe una descripción pública breve para tu perfil.',
    choosePreset: 'Preset de portada',
    presets: {
      aurora: 'Aurora',
      mesh: 'Malla',
      wave: 'Ola',
      grid: 'Cuadrícula'
    },
    uploadBanner: 'Subir banner',
    replaceBanner: 'Cambiar banner',
    removeBanner: 'Quitar banner',
    saveProfile: 'Guardar cambios',
    profileUpdated: 'Perfil actualizado',
    avatarUpdated: 'Avatar actualizado',
    bannerUpdated: 'Banner actualizado',
    bannerRemoved: 'Banner eliminado',
    level: 'Nivel',
    xp: 'XP',
    currentStreak: 'Racha actual',
    bestStreak: 'Mejor racha',
    completedExams: 'Tests completados',
    completedPractice: 'Prácticas',
    perfectScores: 'Resultados perfectos',
    badges: 'Insignias',
    noBadges: 'Las insignias aparecerán después de completar tests.',
    followers: 'Seguidores',
    following: 'Siguiendo',
    openFollowers: 'Abrir seguidores',
    openFollowing: 'Abrir seguidos',
    follow: 'Seguir',
    unfollow: 'Dejar de seguir',
    creatorStats: 'Estadísticas del creador',
    publicRating: 'Valoración pública',
    publicPlays: 'Intentos públicos',
    publishedTests: 'Tests publicados',
    publicTests: 'Tests públicos',
    viewAllPublished: 'Ver todos',
    noPublicTests: 'Todavía no hay tests públicos.',
    loadingProfiles: 'Cargando lista...',
    noFollowers: 'Todavía no hay seguidores.',
    noFollowing: 'Todavía no hay suscripciones.',
    profileLoadError: 'No se pudo cargar el perfil',
    saveError: 'No se pudo guardar el perfil',
    followError: 'No se pudo actualizar el seguimiento',
    joined: 'Miembro desde',
    uniqueId: 'ID',
    about: 'Acerca del perfil',
    overview: 'Resumen',
    security: 'Seguridad',
    comments: 'Comentarios',
    publicProgress: 'Progreso público',
    creatorPortfolio: 'Portafolio del creador',
    tabOverview: 'Resumen',
    tabAccount: 'Perfil',
    tabAppearance: 'Apariencia',
    tabSecurity: 'Seguridad',
    tabActivity: 'Actividad',
    tabOverviewDesc: 'Tu resumen y estadísticas de creador',
    tabAccountDesc: 'Identidad, username, biografía',
    tabAppearanceDesc: 'Portada, tema e idioma',
    tabSecurityDesc: 'Contraseña y seguridad de la cuenta',
    tabActivityDesc: 'Avisos, comentarios e historial',
    overviewHeadline: 'Bienvenido de vuelta',
    overviewSubtitle: 'Una mirada rápida a tu progreso y trabajo como creador.',
    accountHeadline: 'Datos de la cuenta',
    accountSubtitle: 'Información pública visible en la plataforma.',
    appearanceHeadline: 'Apariencia',
    appearanceSubtitle: 'Personaliza cómo se ve tu perfil ante los demás.',
    securityHeadline: 'Seguridad',
    securitySubtitle: 'Mantén tu cuenta segura.',
    activityHeadline: 'Historial de actividad',
    activitySubtitle: 'Avisos, comentarios y logros.',
    seeAll: 'Ver todo',
    noActivity: 'Aún no hay actividad.',
    copyId: 'Copiar ID',
    idCopied: 'ID copiado',
    tabPublicOverview: 'Resumen',
    tabPublicTests: 'Tests',
    tabPublicAchievements: 'Logros',
    tabPublicOverviewDesc: 'Resumen y estadísticas del creador',
    tabPublicTestsDesc: 'Tests públicos publicados',
    tabPublicAchievementsDesc: 'Insignias e hitos desbloqueados',
    publicOverviewSubtitle: 'Vista rápida del perfil público.',
    publicTestsSubtitle: 'Todos los tests públicos de este creador.',
    publicAchievementsSubtitle: 'Insignias desbloqueadas en la plataforma.'
  }
};

export const profileBadgeLabels = {
  first_completion: {
    en: 'First completion',
    ru: 'Первое завершение',
    kz: 'Алғашқы аяқтау',
    es: 'Primera finalización'
  },
  three_day_streak: {
    en: '3-day streak',
    ru: 'Серия 3 дня',
    kz: '3 күндік серия',
    es: 'Racha de 3 días'
  },
  ten_completed: {
    en: '10 completed tests',
    ru: '10 завершённых тестов',
    kz: '10 аяқталған тест',
    es: '10 tests completados'
  },
  perfect_score: {
    en: 'Perfect score',
    ru: 'Идеальный результат',
    kz: 'Мінсіз нәтиже',
    es: 'Puntuación perfecta'
  },
  first_arena: {
    en: 'First arena',
    ru: 'Первая арена',
    kz: 'Алғашқы арена',
    es: 'Primera arena'
  },
  arena_winner: {
    en: 'Arena winner',
    ru: 'Победа в арене',
    kz: 'Арена жеңімпазы',
    es: 'Ganador de arena'
  },
  duel_winner: {
    en: 'Duel winner',
    ru: 'Победа в дуэли',
    kz: 'Дуэль жеңімпазы',
    es: 'Ganador del duelo'
  }
};
