export const profileCopy = {
  en: {
    headline: 'Headline',
    bio: 'Bio',
    headlinePlaceholder: 'Short line that introduces you as a creator or learner',
    bioPlaceholder: 'Write a short public description for your profile.',
    choosePreset: 'Cover preset',
    presets: {
      aurora: 'Aurora',
      mesh: 'Mesh',
      wave: 'Wave',
      grid: 'Grid'
    },
    uploadBanner: 'Upload banner',
    replaceBanner: 'Replace banner',
    removeBanner: 'Remove banner',
    saveProfile: 'Save changes',
    profileUpdated: 'Profile updated',
    avatarUpdated: 'Avatar updated',
    bannerUpdated: 'Banner updated',
    bannerRemoved: 'Banner removed',
    level: 'Level',
    xp: 'XP',
    currentStreak: 'Current streak',
    bestStreak: 'Best streak',
    completedExams: 'Completed tests',
    completedPractice: 'Practice runs',
    perfectScores: 'Perfect scores',
    badges: 'Badges',
    noBadges: 'Badges will appear after completed tests.',
    followers: 'Followers',
    following: 'Following',
    openFollowers: 'Open followers',
    openFollowing: 'Open following',
    follow: 'Follow',
    unfollow: 'Unfollow',
    creatorStats: 'Creator stats',
    publicRating: 'Public rating',
    publicPlays: 'Public plays',
    publishedTests: 'Published tests',
    publicTests: 'Public tests',
    viewAllPublished: 'View all',
    noPublicTests: 'No public tests yet.',
    loadingProfiles: 'Loading list...',
    noFollowers: 'No followers yet.',
    noFollowing: 'No subscriptions yet.',
    profileLoadError: 'Failed to load profile',
    saveError: 'Failed to save profile',
    followError: 'Failed to update follow status',
    joined: 'Joined',
    uniqueId: 'ID',
    about: 'About',
    overview: 'Overview',
    security: 'Security',
    comments: 'Comments',
    publicProgress: 'Public progress',
    creatorPortfolio: 'Creator portfolio'
  },
  ru: {
    headline: 'Заголовок профиля',
    bio: 'О себе',
    headlinePlaceholder: 'Коротко опиши себя как автора или ученика',
    bioPlaceholder: 'Добавь публичное описание профиля.',
    choosePreset: 'Пресет обложки',
    presets: {
      aurora: 'Аврора',
      mesh: 'Сетка',
      wave: 'Волна',
      grid: 'Грид'
    },
    uploadBanner: 'Загрузить баннер',
    replaceBanner: 'Заменить баннер',
    removeBanner: 'Удалить баннер',
    saveProfile: 'Сохранить изменения',
    profileUpdated: 'Профиль обновлён',
    avatarUpdated: 'Аватар обновлён',
    bannerUpdated: 'Баннер обновлён',
    bannerRemoved: 'Баннер удалён',
    level: 'Уровень',
    xp: 'XP',
    currentStreak: 'Текущая серия',
    bestStreak: 'Лучшая серия',
    completedExams: 'Завершённые тесты',
    completedPractice: 'Тренировки',
    perfectScores: 'Идеальные результаты',
    badges: 'Достижения',
    noBadges: 'Достижения появятся после завершённых тестов.',
    followers: 'Подписчики',
    following: 'Подписки',
    openFollowers: 'Открыть подписчиков',
    openFollowing: 'Открыть подписки',
    follow: 'Подписаться',
    unfollow: 'Отписаться',
    creatorStats: 'Статистика автора',
    publicRating: 'Рейтинг публичных тестов',
    publicPlays: 'Публичные прохождения',
    publishedTests: 'Опубликованные тесты',
    publicTests: 'Публичные тесты',
    viewAllPublished: 'Смотреть все',
    noPublicTests: 'Публичных тестов пока нет.',
    loadingProfiles: 'Загрузка списка...',
    noFollowers: 'Подписчиков пока нет.',
    noFollowing: 'Подписок пока нет.',
    profileLoadError: 'Не удалось загрузить профиль',
    saveError: 'Не удалось сохранить профиль',
    followError: 'Не удалось обновить подписку',
    joined: 'На платформе с',
    uniqueId: 'ID',
    about: 'О профиле',
    overview: 'Обзор',
    security: 'Безопасность',
    comments: 'Комментарии',
    publicProgress: 'Публичный прогресс',
    creatorPortfolio: 'Портфолио автора'
  },
  kz: {
    headline: 'Профиль тақырыбы',
    bio: 'Өзің туралы',
    headlinePlaceholder: 'Өзіңді автор немесе оқушы ретінде қысқаша таныстыр',
    bioPlaceholder: 'Профильге қысқа ашық сипаттама жаз.',
    choosePreset: 'Мұқаба пресеті',
    presets: {
      aurora: 'Аврора',
      mesh: 'Тор',
      wave: 'Толқын',
      grid: 'Грид'
    },
    uploadBanner: 'Баннер жүктеу',
    replaceBanner: 'Баннерді ауыстыру',
    removeBanner: 'Баннерді өшіру',
    saveProfile: 'Өзгерістерді сақтау',
    profileUpdated: 'Профиль жаңартылды',
    avatarUpdated: 'Аватар жаңартылды',
    bannerUpdated: 'Баннер жаңартылды',
    bannerRemoved: 'Баннер өшірілді',
    level: 'Деңгей',
    xp: 'XP',
    currentStreak: 'Қазіргі серия',
    bestStreak: 'Ең үздік серия',
    completedExams: 'Аяқталған тесттер',
    completedPractice: 'Жаттығулар',
    perfectScores: 'Мінсіз нәтижелер',
    badges: 'Жетістіктер',
    noBadges: 'Жетістіктер тесттерді аяқтағаннан кейін шығады.',
    followers: 'Жазылушылар',
    following: 'Жазылымдар',
    openFollowers: 'Жазылушыларды ашу',
    openFollowing: 'Жазылымдарды ашу',
    follow: 'Жазылу',
    unfollow: 'Жазылымнан шығу',
    creatorStats: 'Автор статистикасы',
    publicRating: 'Қоғамдық тест рейтингі',
    publicPlays: 'Қоғамдық өтулер',
    publishedTests: 'Жарияланған тесттер',
    publicTests: 'Қоғамдық тесттер',
    viewAllPublished: 'Барлығын көру',
    noPublicTests: 'Қоғамдық тесттер әлі жоқ.',
    loadingProfiles: 'Тізім жүктелуде...',
    noFollowers: 'Әлі жазылушылар жоқ.',
    noFollowing: 'Әлі жазылымдар жоқ.',
    profileLoadError: 'Профильді жүктеу мүмкін болмады',
    saveError: 'Профильді сақтау мүмкін болмады',
    followError: 'Жазылым күйін жаңарту мүмкін болмады',
    joined: 'Қосылған күні',
    uniqueId: 'ID',
    about: 'Профиль туралы',
    overview: 'Шолу',
    security: 'Қауіпсіздік',
    comments: 'Пікірлер',
    publicProgress: 'Ашық прогресс',
    creatorPortfolio: 'Автор портфолиосы'
  },
  es: {
    headline: 'Título del perfil',
    bio: 'Biografía',
    headlinePlaceholder: 'Una línea corta sobre ti como creador o estudiante',
    bioPlaceholder: 'Escribe una descripción pública breve para tu perfil.',
    choosePreset: 'Preset de portada',
    presets: {
      aurora: 'Aurora',
      mesh: 'Malla',
      wave: 'Ola',
      grid: 'Cuadrícula'
    },
    uploadBanner: 'Subir banner',
    replaceBanner: 'Cambiar banner',
    removeBanner: 'Quitar banner',
    saveProfile: 'Guardar cambios',
    profileUpdated: 'Perfil actualizado',
    avatarUpdated: 'Avatar actualizado',
    bannerUpdated: 'Banner actualizado',
    bannerRemoved: 'Banner eliminado',
    level: 'Nivel',
    xp: 'XP',
    currentStreak: 'Racha actual',
    bestStreak: 'Mejor racha',
    completedExams: 'Tests completados',
    completedPractice: 'Prácticas',
    perfectScores: 'Resultados perfectos',
    badges: 'Insignias',
    noBadges: 'Las insignias aparecerán después de completar tests.',
    followers: 'Seguidores',
    following: 'Siguiendo',
    openFollowers: 'Abrir seguidores',
    openFollowing: 'Abrir seguidos',
    follow: 'Seguir',
    unfollow: 'Dejar de seguir',
    creatorStats: 'Estadísticas del creador',
    publicRating: 'Valoración pública',
    publicPlays: 'Intentos públicos',
    publishedTests: 'Tests publicados',
    publicTests: 'Tests públicos',
    viewAllPublished: 'Ver todos',
    noPublicTests: 'Todavía no hay tests públicos.',
    loadingProfiles: 'Cargando lista...',
    noFollowers: 'Todavía no hay seguidores.',
    noFollowing: 'Todavía no hay suscripciones.',
    profileLoadError: 'No se pudo cargar el perfil',
    saveError: 'No se pudo guardar el perfil',
    followError: 'No se pudo actualizar el seguimiento',
    joined: 'Miembro desde',
    uniqueId: 'ID',
    about: 'Acerca del perfil',
    overview: 'Resumen',
    security: 'Seguridad',
    comments: 'Comentarios',
    publicProgress: 'Progreso público',
    creatorPortfolio: 'Portafolio del creador'
  }
};

export const profileBadgeLabels = {
  first_completion: {
    en: 'First completion',
    ru: 'Первое завершение',
    kz: 'Алғашқы аяқтау',
    es: 'Primera finalización'
  },
  three_day_streak: {
    en: '3-day streak',
    ru: 'Серия 3 дня',
    kz: '3 күндік серия',
    es: 'Racha de 3 días'
  },
  ten_completed: {
    en: '10 completed tests',
    ru: '10 завершённых тестов',
    kz: '10 аяқталған тест',
    es: '10 tests completados'
  },
  perfect_score: {
    en: 'Perfect score',
    ru: 'Идеальный результат',
    kz: 'Мінсіз нәтиже',
    es: 'Puntuación perfecta'
  },
  first_arena: {
    en: 'First arena',
    ru: 'Первая арена',
    kz: 'Алғашқы арена',
    es: 'Primera arena'
  },
  arena_winner: {
    en: 'Arena winner',
    ru: 'Победа в арене',
    kz: 'Арена жеңімпазы',
    es: 'Ganador de arena'
  },
  duel_winner: {
    en: 'Duel winner',
    ru: 'Победа в дуэли',
    kz: 'Дуэль жеңімпазы',
    es: 'Ganador del duelo'
  }
};
