import { createContext, useContext, useState, useEffect, useCallback } from 'react';

const translations = {
  en: {
    // Navbar
    home: 'Home',
    myTests: 'My Tests',
    results: 'Results',
    questionBank: 'Question Bank',
    groups: 'Groups',
    createTest: 'Create Test',
    profile: 'Profile',
    admin: 'Admin',
    logout: 'Log out',
    teacher: 'Teacher',
    student: 'Student',
    adminRole: 'Admin',
    lightTheme: 'Light theme',
    darkTheme: 'Dark theme',
    // Dashboard
    welcome: 'Welcome',
    dashboardSubtitle: 'Access knowledge and track your progress',
    searchTests: 'Search tests...',
    newest: 'Newest',
    popular: 'Popular',
    rating: 'Rating',
    noTests: 'No tests yet',
    createFirst: 'Create your first test right now',
    publicTest: 'Public',
    privateTest: 'Private',
    questions: 'questions',
    noDescription: 'No description',
    deleteTest: 'Delete test',
    deleteTestConfirm: 'Delete this test? All results will also be deleted.',
    delete: 'Delete',
    edit: 'Edit',
    copyLink: 'Copy link',
    linkCopied: 'Link copied!',
    // Leaderboard
    leaderboard: 'Rating',
    totalParticipants: 'Total participants',
    emptyLeaderboard: 'Empty yet',
    noOneCompleted: 'No one has taken this test yet',
    error: 'Error',
    toHome: 'To home',
    // Auth
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    firstName: 'First name',
    lastName: 'Last name',
    middleName: 'Middle name',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    loginBtn: 'Log in',
    registerBtn: 'Register',
    // Profile
    profileTitle: 'Profile',
    editProfile: 'Edit profile',
    changePassword: 'Change password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    save: 'Save',
    cancel: 'Cancel',
    language: 'Language',
    uploadAvatar: 'Upload avatar',
    warnings: 'Warnings',
    memberSince: 'Member since',
    // General
    loading: 'Loading...',
    errorLoading: 'Loading error',
    back: 'Back',
    // Test
    startTest: 'Start Test',
    submitTest: 'Submit',
    nextQuestion: 'Next',
    prevQuestion: 'Previous',
    timeLeft: 'Time left',
    question: 'Question',
    of: 'of',
    // Comments
    comments: 'Comments',
    addComment: 'Add comment',
    writeComment: 'Write a comment...',
    send: 'Send',
    reply: 'Reply',
    commentsDisabled: 'Comments are disabled',
    deleteComment: 'Delete',
    // Admin
    adminPanel: 'Admin Panel',
    users: 'Users',
    tests: 'Tests',
    statistics: 'Statistics',
    ban: 'Ban',
    unban: 'Unban',
    warn: 'Warn',
    banned: 'Banned',
    role: 'Role',
    search: 'Search',
    totalUsers: 'Total users',
    totalTests: 'Total tests',
    totalResults: 'Total results',
    bannedUsers: 'Banned users',
    changeRole: 'Change role',
    banUser: 'Ban user',
    banReason: 'Ban reason',
    warnMessage: 'Warning message',
    recentUsers: 'Recent users',
    recentTests: 'Recent tests',
    // Results
    testResults: 'Test Results',
    score: 'Score',
    passed: 'Passed',
    failed: 'Failed',
    viewResults: 'View Results',
    // Notifications
    notifications: 'Notifications',
    noNotifications: 'No notifications',
    markAllRead: 'Mark all as read',
    // Reports
    report: 'Report',
    reportReason: 'Reason for report',
    reportSent: 'Report sent',
    reportTest: 'Report test',
    reportComment: 'Report comment',
    reportUser: 'Report user',
    // Comments extended
    editComment: 'Edit',
    cancelEditConfirm: 'Discard changes?',
    edited: 'edited',
    testCreator: 'Author',
    // User profile
    userProfile: 'User Profile',
    testsCreated: 'Tests created',
    testsTaken: 'Tests taken',
    // Export
    exportCSV: 'CSV',
    exportJSON: 'JSON',
    exportPDF: 'PDF',
    // Auto-save
    draftFound: 'Draft found',
    restoreDraft: 'Restore draft?',
    restore: 'Restore',
    discard: 'Discard',
    instantFeedback: 'Instant check',
    instantFeedbackDesc: 'Shows the correct answer immediately after answering',
    correct: 'Correct',
    incorrect: 'Incorrect',
    checkAnswer: 'Check answer',
    explanation: 'Explanation',
    // Passage
    addPassage: 'Add reading text',
    hidePassage: 'Hide reading text',
    passage: 'Reading text',
    passagePlaceholder: 'Enter a reading passage/text that will be shown above the question...',
    passageLabel: 'Text',
    // Question types
    singleChoice: 'Single answer',
    multipleChoice: 'Multiple answers',
    trueFalse: 'True / False',
    essay: 'Essay',
    matching: 'Matching',
    fillBlank: 'Fill in the blank',
    // True-false options
    optTrue: 'True',
    optFalse: 'False',
    optNotSure: 'Not sure',
    // CreateTest
    minOneQuestion: 'Minimum 1 question',
    enterTestTitle: 'Enter test title',
    fillAllQuestions: 'Fill in all questions',
    testUpdated: 'Test updated!',
    testCreated: 'Test created!',
    errorSaving: 'Error saving',
    mediaUploaded: 'Media uploaded',
    errorUploadMedia: 'Error uploading media',
    importedQuestions: 'Imported questions',
    cannotParseQuestions: 'Could not parse questions. Check the format.',
    errorReadingFile: 'Error reading file',
    errorLoadingBank: 'Error loading bank',
    addedFromBank: 'Added questions from bank',
    savedToBank: 'Questions saved to bank',
    errorSavingToBank: 'Error saving to bank',
    deleteQuestion: 'Delete question',
    deleteQuestionConfirm: 'Delete question #{{num}}? This action cannot be undone.',
    navigation: 'Navigation',
    questionsCount: 'Questions',
    pointsCount: 'Points',
    fromQuestionBank: 'From question bank',
    importCSV: 'Import CSV',
    saveToBank: 'Save to bank',
    aiGenerate: 'AI Generate',
    aiGenerateDesc: 'Create questions from text or image',
    aiTextInput: 'Text content',
    aiTextPlaceholder: 'Paste text, lecture notes, or any content to generate questions from...',
    aiImageInput: 'Image (screenshot, textbook page)',
    aiUploadImage: 'Upload image',
    aiQuestionCount: 'Questions',
    aiQuestionTypes: 'Question types',
    aiGenerateBtn: 'Generate',
    aiGenerating: 'Generating...',
    aiPoweredBy: 'Powered by Azure OpenAI',
    aiProvideContent: 'Provide text or upload an image',
    aiNoQuestions: 'AI returned no questions. Try again.',
    aiFileTooLarge: 'File too large (max 10MB)',
    aiQuestionsAdded: '{{count}} questions added!',
    editTest: 'Edit test',
    settings: 'Settings',
    update: 'Update',
    testSettings: 'Test settings',
    timeLimitMin: 'Time limit (min)',
    maxAttempts: 'Max attempts',
    maxViolations: 'Max violations',
    isPublic: 'Public',
    shuffleQuestions: 'Shuffle questions',
    shuffleOptions: 'Shuffle options',
    showResults: 'Show results',
    blockTabSwitch: 'Block tabs',
    blockCopyPaste: 'Block copy',
    blockScreenshot: 'Block screenshots',
    testTitlePlaceholder: 'Test title...',
    testDescPlaceholder: 'Test description (optional)...',
    newQuestion: 'New question...',
    questionTextPlaceholder: 'Question text...',
    addMedia: 'Add media (photo, video, audio)',
    optionPlaceholder: 'Option',
    addOption: 'Add option',
    essayHint: 'Student will write a detailed answer. Manually graded by teacher.',
    correctAnswer: 'Correct answer',
    enterCorrectAnswer: 'Enter correct answer',
    element: 'Element',
    pair: 'Pair',
    addPair: 'Add pair',
    explanationPlaceholder: 'Explanation for the answer (optional)...',
    addQuestion: 'Add question',
    updateTest: 'Update test',
    saveTest: 'Save test',
    importFromCSV: 'Import from CSV',
    clickToSelectFile: 'Click to select file',
    questionBankTitle: 'Question bank',
    bankEmpty: 'Bank is empty. Save questions from a test for them to appear here.',
    selectQuestions: 'Select questions',
    addSelected: 'Add selected',
    close: 'Close',
    points: 'points',
    savingDraft: 'Saving...',
    draftSaved: 'Draft saved',
    noLimitPlaceholder: '0 = no limit',
    startDate: 'Start date',
    endDate: 'End date',
    questionPoolSize: 'Questions from pool',
    poolSizeHint: '0 = all questions',
    inactivityTimeout: 'Inactivity timeout (min)',
    inactivityHint: '0 = disabled',
    practiceMode: 'Practice mode',
    practiceModeDesc: 'Training mode — unlimited attempts, results not saved',
    practiceModeLabel: 'Practice',
    partialCredit: 'Partial credit',
    partialCreditDesc: 'Award partial points for partially correct multiple-choice/matching answers',
    changeTicket: 'Change ticket',
    ticketHintPublic: 'Choose any ticket. Each ticket is available to everyone.',
    aiHistory: 'History',
    aiNoHistory: 'No generation history yet',
    clearAll: 'Clear all',
    exportJSON: 'Export JSON',
    importJSON: 'Import JSON',
    exportSuccess: 'Test exported!',
    importSuccess: 'Test imported!',
    importError: 'Import error — invalid file',
    preview: 'Preview',
    previewMode: 'Preview mode — results not saved',
    inactivityWarning: 'Are you still there?',
    inactivityCountdownMsg: 'Test will auto-submit in {{seconds}} sec',
    imHere: "I'm here!",
    category: 'Category',
    allCategories: 'All categories',
    // Ticket system
    ticketN: 'Ticket #{{n}}',
    chooseTicket: 'Choose your ticket',
    ticketReady: 'Your ticket is locked in. Press Start!',
    claimingTicket: 'Claiming ticket...',
    ticketHint: 'Green — available, Red — taken. Choose quickly!',
    variantsEnabled: 'Ticket/Variant System',
    variantCount: 'Number of variants',
    variantsHint: 'Each student gets a unique ticket with shuffled questions',
    // TakeTest
    matchingHint: 'Click an item on the left, then its pair on the right. Matched pairs are highlighted.',
    elements: 'Elements',
    pairs: 'Pairs',
    yourPairs: 'Your pairs:',
    violationLimitExceeded: 'Violation limit exceeded! Test auto-submitted.',
    timeUp: 'Time is up!',
    testNotFound: 'Test not found',
    enterYourName: 'Enter your name',
    errorCheckingAnswer: 'Error checking answer',
    errorSubmitting: 'Error submitting',
    point: 'point',
    multipleAnswersHint: 'You can select multiple options',
    checking: 'Checking...',
    writeYourAnswer: 'Write your answer...',
    essayCheckedByTeacher: 'Essay is checked by teacher after submission',
    enterAnswer: 'Enter answer...',
    correctAnswerIs: 'Correct answer',
    explanationLabel: 'Explanation:',
    correctBanner: 'Correct!',
    incorrectBanner: 'Incorrect',
    outOfPoints: 'out of',
    finishTest: 'Finish test',
    finishTestTitle: 'Finish test',
    finishTestMessage: 'You answered {{answered}} of {{total}} questions. Finish and submit answers?',
    finishBtn: 'Finish',
    continueTest: 'Continue test',
    startTestBtn: 'Start test',
    yourName: 'Your name',
    enterFullName: 'Enter your full name',
    attempts: 'Attempts',
    allAttemptsUsed: 'All attempts used',
    testRules: 'Test rules:',
    ruleNoLeave: 'You cannot leave the test page (switch tabs, minimize browser)',
    ruleViolationsTracked: 'Each violation is recorded and visible to the teacher',
    ruleMaxViolations: 'Max violations: {{max}} — after that the test ends automatically',
    modeInstantFeedback: 'Mode: Instant check',
    instantFeedbackInfo: 'After each answer you will see if it is correct. You cannot change the answer after checking.',
    answered: 'answered',
    selectOption: 'select',
    navigation: 'navigate',
    violation: 'Violation!',
    violationCount: 'Violation {{current}} of {{max}}',
    understood: 'Understood',
    next: 'Next',
    prev: 'Back',
    // TestProfile
    questionTypes: 'Question types',
    rateTest: 'Rate this test',
    yourRating: 'Your rating',
    clickToRate: 'Click to rate',
    loginToRate: 'Log in to rate the test',
    ratingUpdated: 'Rating updated',
    thanksForRating: 'Thanks for rating!',
    tabSwitchBlocked: 'Tab switching is blocked. Max violations',
    allAttemptsUsedFull: 'You have used all attempts',
    viewAll: 'All →',
    min: 'min',
    // Validation
    noCorrectAnswer: 'Question {{num}}: mark the correct answer',
    emptyOptions: 'Question {{num}}: fill in all answer options',
    // Dashboard
    errorLoadingTests: 'Error loading tests',
    testDeleted: 'Test deleted',
    errorDeleting: 'Error deleting',
    deleteTestTitle: 'Delete test',
    deleteTestMsg: 'Delete this test? All results will also be deleted.',
  },
  ru: {
    home: 'Главная',
    myTests: 'Мои тесты',
    results: 'Результаты',
    questionBank: 'Банк вопросов',
    groups: 'Группы',
    createTest: 'Создать тест',
    profile: 'Профиль',
    admin: 'Админ',
    logout: 'Выйти',
    teacher: 'Преподаватель',
    student: 'Студент',
    adminRole: 'Админ',
    lightTheme: 'Светлая тема',
    darkTheme: 'Тёмная тема',
    welcome: 'Добро пожаловать',
    dashboardSubtitle: 'Откройте доступ к знаниям и отслеживайте результаты',
    searchTests: 'Поиск тестов...',
    newest: 'Новые',
    popular: 'Популярные',
    rating: 'Рейтинг',
    noTests: 'Тестов пока нет',
    createFirst: 'Создайте свой первый тест прямо сейчас',
    publicTest: 'Публичный',
    privateTest: 'Приватный',
    questions: 'вопросов',
    noDescription: 'Без описания',
    deleteTest: 'Удалить тест',
    deleteTestConfirm: 'Удалить этот тест? Все результаты также будут удалены.',
    delete: 'Удалить',
    edit: 'Редактировать',
    copyLink: 'Скопировать',
    linkCopied: 'Ссылка скопирована!',
    leaderboard: 'Рейтинг',
    totalParticipants: 'Всего участников',
    emptyLeaderboard: 'Пока пусто',
    noOneCompleted: 'Никто ещё не прошёл этот тест',
    error: 'Ошибка',
    toHome: 'На главную',
    login: 'Вход',
    register: 'Регистрация',
    email: 'Email',
    password: 'Пароль',
    firstName: 'Имя',
    lastName: 'Фамилия',
    middleName: 'Отчество',
    noAccount: 'Нет аккаунта?',
    haveAccount: 'Уже есть аккаунт?',
    loginBtn: 'Войти',
    registerBtn: 'Зарегистрироваться',
    profileTitle: 'Профиль',
    editProfile: 'Редактировать профиль',
    changePassword: 'Изменить пароль',
    currentPassword: 'Текущий пароль',
    newPassword: 'Новый пароль',
    save: 'Сохранить',
    cancel: 'Отмена',
    language: 'Язык',
    uploadAvatar: 'Загрузить аватар',
    warnings: 'Предупреждения',
    memberSince: 'Участник с',
    loading: 'Загрузка...',
    errorLoading: 'Ошибка загрузки',
    back: 'Назад',
    startTest: 'Начать тест',
    submitTest: 'Отправить',
    nextQuestion: 'Далее',
    prevQuestion: 'Назад',
    timeLeft: 'Осталось',
    question: 'Вопрос',
    of: 'из',
    comments: 'Комментарии',
    addComment: 'Добавить комментарий',
    writeComment: 'Напишите комментарий...',
    send: 'Отправить',
    reply: 'Ответить',
    commentsDisabled: 'Комментарии отключены',
    deleteComment: 'Удалить',
    adminPanel: 'Панель администратора',
    users: 'Пользователи',
    tests: 'Тесты',
    statistics: 'Статистика',
    ban: 'Заблокировать',
    unban: 'Разблокировать',
    warn: 'Предупредить',
    banned: 'Заблокирован',
    role: 'Роль',
    search: 'Поиск',
    totalUsers: 'Всего пользователей',
    totalTests: 'Всего тестов',
    totalResults: 'Всего результатов',
    bannedUsers: 'Заблокировано',
    changeRole: 'Изменить роль',
    banUser: 'Заблокировать пользователя',
    banReason: 'Причина блокировки',
    warnMessage: 'Сообщение предупреждения',
    recentUsers: 'Новые пользователи',
    recentTests: 'Новые тесты',
    testResults: 'Результаты теста',
    score: 'Баллы',
    passed: 'Сдано',
    failed: 'Не сдано',
    viewResults: 'Результаты',
    notifications: 'Уведомления',
    noNotifications: 'Нет уведомлений',
    markAllRead: 'Прочитать все',
    report: 'Пожаловаться',
    reportReason: 'Причина жалобы',
    reportSent: 'Жалоба отправлена',
    reportTest: 'Пожаловаться на тест',
    reportComment: 'Пожаловаться на комментарий',
    reportUser: 'Пожаловаться на пользователя',
    editComment: 'Редактировать',
    cancelEditConfirm: 'Отменить изменения?',
    edited: 'изменено',
    testCreator: 'Автор',
    userProfile: 'Профиль пользователя',
    testsCreated: 'Тестов создано',
    testsTaken: 'Тестов пройдено',
    exportCSV: 'CSV',
    exportJSON: 'JSON',
    exportPDF: 'PDF',
    draftFound: 'Найден черновик',
    restoreDraft: 'Восстановить черновик?',
    restore: 'Восстановить',
    discard: 'Удалить',
    instantFeedback: 'Мгновенная проверка',
    instantFeedbackDesc: 'Показывает правильный ответ сразу после ответа',
    correct: 'Правильно',
    incorrect: 'Неправильно',
    checkAnswer: 'Проверить ответ',
    explanation: 'Пояснение',
    // Passage
    addPassage: 'Добавить текст для чтения',
    hidePassage: 'Скрыть текст',
    passage: 'Текст для чтения',
    passagePlaceholder: 'Введите текст/отрывок, который будет показан над вопросом...',
    passageLabel: 'Текст',
    // Question types
    singleChoice: 'Один ответ',
    multipleChoice: 'Несколько ответов',
    trueFalse: 'Верно / Неверно',
    essay: 'Эссе',
    matching: 'Сопоставление',
    fillBlank: 'Заполнить пропуск',
    // True-false options
    optTrue: 'Верно',
    optFalse: 'Неверно',
    optNotSure: 'Не уверен в ответе',
    // CreateTest
    minOneQuestion: 'Минимум 1 вопрос',
    enterTestTitle: 'Введите название теста',
    fillAllQuestions: 'Заполните все вопросы',
    testUpdated: 'Тест обновлён!',
    testCreated: 'Тест создан!',
    errorSaving: 'Ошибка сохранения',
    mediaUploaded: 'Медиа загружено',
    errorUploadMedia: 'Ошибка загрузки медиа',
    importedQuestions: 'Импортировано вопросов',
    cannotParseQuestions: 'Не удалось распознать вопросы. Проверьте формат.',
    errorReadingFile: 'Ошибка чтения файла',
    errorLoadingBank: 'Ошибка загрузки банка',
    addedFromBank: 'Добавлено вопросов из банка',
    savedToBank: 'Вопросы сохранены в банк',
    errorSavingToBank: 'Ошибка сохранения в банк',
    deleteQuestion: 'Удалить вопрос',
    deleteQuestionConfirm: 'Удалить вопрос №{{num}}? Это действие нельзя отменить.',
    navigation: 'Навигация',
    questionsCount: 'Вопросов',
    pointsCount: 'Баллов',
    fromQuestionBank: 'Из банка вопросов',
    importCSV: 'Импорт CSV',
    saveToBank: 'Сохранить в банк',
    aiGenerate: 'AI Генерация',
    aiGenerateDesc: 'Создать вопросы из текста или картинки',
    aiTextInput: 'Текстовый контент',
    aiTextPlaceholder: 'Вставьте текст, конспект, или любой материал для генерации вопросов...',
    aiImageInput: 'Картинка (скриншот, страница учебника)',
    aiUploadImage: 'Загрузить картинку',
    aiQuestionCount: 'Кол-во вопросов',
    aiQuestionTypes: 'Типы вопросов',
    aiGenerateBtn: 'Сгенерировать',
    aiGenerating: 'Генерация...',
    aiPoweredBy: 'Azure OpenAI',
    aiProvideContent: 'Введите текст или загрузите картинку',
    aiNoQuestions: 'AI не вернул вопросы. Попробуйте еще раз.',
    aiFileTooLarge: 'Файл слишком большой (макс 10МБ)',
    aiQuestionsAdded: '{{count}} вопросов добавлено!',
    editTest: 'Редактировать тест',
    settings: 'Настройки',
    update: 'Обновить',
    testSettings: 'Настройки теста',
    timeLimitMin: 'Время теста (мин)',
    maxAttempts: 'Макс. попыток',
    maxViolations: 'Макс. нарушений',
    isPublic: 'Публичный',
    shuffleQuestions: 'Перемешать вопросы',
    shuffleOptions: 'Перемешать ответы',
    showResults: 'Показать результаты',
    blockTabSwitch: 'Блок. вкладки',
    blockCopyPaste: 'Блок. копирование',
    blockScreenshot: 'Блок. скриншоты',
    testTitlePlaceholder: 'Название теста...',
    testDescPlaceholder: 'Описание теста (необязательно)...',
    newQuestion: 'Новый вопрос...',
    questionTextPlaceholder: 'Текст вопроса...',
    addMedia: 'Добавить медиа (фото, видео, аудио)',
    optionPlaceholder: 'Вариант',
    addOption: 'Добавить вариант',
    essayHint: 'Студент напишет развёрнутый ответ. Проверка преподавателем вручную.',
    correctAnswer: 'Правильный ответ',
    enterCorrectAnswer: 'Введите правильный ответ',
    element: 'Элемент',
    pair: 'Пара',
    addPair: 'Добавить пару',
    explanationPlaceholder: 'Пояснение к ответу (необязательно)...',
    addQuestion: 'Добавить вопрос',
    updateTest: 'Обновить тест',
    saveTest: 'Сохранить тест',
    importFromCSV: 'Импорт из CSV',
    clickToSelectFile: 'Нажмите, чтобы выбрать файл',
    questionBankTitle: 'Банк вопросов',
    bankEmpty: 'Банк пуст. Сохраните вопросы из теста, чтобы они появились здесь.',
    selectQuestions: 'Выберите вопросы',
    addSelected: 'Добавить выбранные',
    close: 'Закрыть',
    points: 'баллов',
    savingDraft: 'Сохранение...',
    draftSaved: 'Черновик сохранён',
    noLimitPlaceholder: '0 = без лимита',
    startDate: 'Дата начала',
    endDate: 'Дата окончания',
    questionPoolSize: 'Вопросов из пула',
    poolSizeHint: '0 = все вопросы',
    inactivityTimeout: 'Таймаут неактивности (мин)',
    inactivityHint: '0 = выключено',
    practiceMode: 'Режим тренировки',
    practiceModeDesc: 'Тренировка — безлимитные попытки, результаты не сохраняются',
    practiceModeLabel: 'Тренировка',
    partialCredit: 'Частичные баллы',
    partialCreditDesc: 'Начислять частичные баллы за частично правильные ответы (множественный выбор/сопоставление)',
    changeTicket: 'Сменить билет',
    ticketHintPublic: 'Выберите любой билет. Каждый билет доступен для всех.',
    aiHistory: 'История',
    aiNoHistory: 'История генераций пуста',
    clearAll: 'Очистить всё',
    exportJSON: 'Экспорт JSON',
    importJSON: 'Импорт JSON',
    exportSuccess: 'Тест экспортирован!',
    importSuccess: 'Тест импортирован!',
    importError: 'Ошибка импорта — некорректный файл',
    preview: 'Превью',
    previewMode: 'Режим предпросмотра — результат не сохранён',
    inactivityWarning: 'Вы ещё здесь?',
    inactivityCountdownMsg: 'Тест автоматически завершится через {{seconds}} сек',
    imHere: 'Я здесь!',
    category: 'Категория',
    allCategories: 'Все категории',
    // Ticket system
    ticketN: 'Билет #{{n}}',
    chooseTicket: 'Выберите билет',
    ticketReady: 'Билет закреплён за вами. Нажмите Начать!',
    claimingTicket: 'Выбираем билет...',
    ticketHint: 'Зелёный — свободен, Красный — занят. Выбирайте быстрее!',
    variantsEnabled: 'Система билетов/вариантов',
    variantCount: 'Количество вариантов',
    variantsHint: 'Каждый ученик получает уникальный билет с перемешанными вопросами',
    // TakeTest
    matchingHint: 'Нажмите на элемент слева, затем на его пару справа. Совпавшие пары будут выделены одним цветом.',
    elements: 'Элементы',
    pairs: 'Пары',
    yourPairs: 'Ваши пары:',
    violationLimitExceeded: 'Превышен лимит нарушений! Тест автоматически завершён.',
    timeUp: 'Время вышло!',
    testNotFound: 'Тест не найден',
    enterYourName: 'Введите ваше имя',
    errorCheckingAnswer: 'Ошибка проверки ответа',
    errorSubmitting: 'Ошибка отправки',
    point: 'балл',
    multipleAnswersHint: 'Можно выбрать несколько вариантов',
    checking: 'Проверяю...',
    writeYourAnswer: 'Напишите ваш ответ...',
    essayCheckedByTeacher: 'Эссе проверяется преподавателем после завершения',
    enterAnswer: 'Введите ответ...',
    correctAnswerIs: 'Правильный ответ',
    explanationLabel: 'Пояснение:',
    correctBanner: 'Правильно!',
    incorrectBanner: 'Неправильно',
    outOfPoints: 'из',
    finishTest: 'Завершить',
    finishTestTitle: 'Завершить тест',
    finishTestMessage: 'Вы ответили на {{answered}} из {{total}} вопросов. Завершить тест и отправить ответы?',
    finishBtn: 'Завершить',
    continueTest: 'Продолжить тест',
    startTestBtn: 'Начать тест',
    yourName: 'Ваше имя',
    enterFullName: 'Введите ваше полное имя',
    attempts: 'Попытки',
    allAttemptsUsed: 'Все попытки использованы',
    testRules: 'Правила прохождения теста:',
    ruleNoLeave: 'Нельзя покидать страницу теста (переключать вкладки, сворачивать браузер)',
    ruleViolationsTracked: 'Каждое нарушение фиксируется и видно преподавателю',
    ruleMaxViolations: 'Максимум нарушений: {{max}} — после этого тест завершится автоматически',
    modeInstantFeedback: 'Режим: Мгновенная проверка',
    instantFeedbackInfo: 'После каждого ответа вы сразу увидите, правильный ли он. Изменить ответ после проверки нельзя.',
    answered: 'отвечено',
    selectOption: 'выбрать',
    navigation: 'навигация',
    violation: 'Нарушение!',
    violationCount: 'Нарушение {{current}} из {{max}}',
    understood: 'Понятно',
    next: 'Далее',
    prev: 'Назад',
    // TestProfile
    questionTypes: 'Типы вопросов',
    rateTest: 'Оцените тест',
    yourRating: 'Ваша оценка',
    clickToRate: 'Нажмите для оценки',
    loginToRate: 'Войдите, чтобы оценить тест',
    ratingUpdated: 'Оценка обновлена',
    thanksForRating: 'Спасибо за оценку!',
    tabSwitchBlocked: 'Переключение вкладок запрещено. Макс. нарушений',
    allAttemptsUsedFull: 'Вы уже использовали все попытки',
    viewAll: 'Все →',
    min: 'мин',
    // Validation
    noCorrectAnswer: 'Вопрос {{num}}: отметьте правильный ответ',
    emptyOptions: 'Вопрос {{num}}: заполните все варианты ответов',
    // Dashboard
    errorLoadingTests: 'Ошибка загрузки тестов',
    testDeleted: 'Тест удалён',
    errorDeleting: 'Ошибка удаления',
    deleteTestTitle: 'Удалить тест',
    deleteTestMsg: 'Удалить этот тест? Все результаты также будут удалены.',
  },
  kz: {
    home: 'Басты',
    myTests: 'Менің тесттерім',
    results: 'Нәтижелер',
    questionBank: 'Сұрақ банкі',
    groups: 'Топтар',
    createTest: 'Тест құру',
    profile: 'Профиль',
    admin: 'Админ',
    logout: 'Шығу',
    teacher: 'Оқытушы',
    student: 'Студент',
    adminRole: 'Админ',
    lightTheme: 'Жарық тақырып',
    darkTheme: 'Қараңғы тақырып',
    welcome: 'Қош келдіңіз',
    dashboardSubtitle: 'Білімге қол жеткізіңіз және нәтижелерді қадағалаңыз',
    searchTests: 'Тесттерді іздеу...',
    newest: 'Жаңа',
    popular: 'Танымал',
    rating: 'Рейтинг',
    noTests: 'Тесттер жоқ',
    createFirst: 'Бірінші тестіңізді қазір жасаңыз',
    publicTest: 'Жалпыға қолжетімді',
    privateTest: 'Жеке',
    questions: 'сұрақ',
    noDescription: 'Сипаттама жоқ',
    deleteTest: 'Тестті жою',
    deleteTestConfirm: 'Бұл тестті жоюды қалайсыз ба? Барлық нәтижелер де жойылады.',
    delete: 'Жою',
    edit: 'Өңдеу',
    copyLink: 'Көшіру',
    linkCopied: 'Сілтеме көшірілді!',
    leaderboard: 'Рейтинг',
    totalParticipants: 'Барлық қатысушылар',
    emptyLeaderboard: 'Әзірге бос',
    noOneCompleted: 'Бұл тестті әлі ешкім тапсырмаған',
    error: 'Қате',
    toHome: 'Басты бетке',
    login: 'Кіру',
    register: 'Тіркелу',
    email: 'Email',
    password: 'Құпия сөз',
    firstName: 'Аты',
    lastName: 'Тегі',
    middleName: 'Әкесінің аты',
    noAccount: 'Аккаунтыңыз жоқ па?',
    haveAccount: 'Аккаунтыңыз бар ма?',
    loginBtn: 'Кіру',
    registerBtn: 'Тіркелу',
    profileTitle: 'Профиль',
    editProfile: 'Профильді өңдеу',
    changePassword: 'Құпия сөзді өзгерту',
    currentPassword: 'Ағымдағы құпия сөз',
    newPassword: 'Жаңа құпия сөз',
    save: 'Сақтау',
    cancel: 'Бас тарту',
    language: 'Тіл',
    uploadAvatar: 'Аватар жүктеу',
    warnings: 'Ескертулер',
    memberSince: 'Мүше болған уақыт',
    loading: 'Жүктелуде...',
    errorLoading: 'Жүктеу қатесі',
    back: 'Артқа',
    startTest: 'Тестті бастау',
    submitTest: 'Жіберу',
    nextQuestion: 'Келесі',
    prevQuestion: 'Алдыңғы',
    timeLeft: 'Қалған уақыт',
    question: 'Сұрақ',
    of: '/',
    comments: 'Пікірлер',
    addComment: 'Пікір қосу',
    writeComment: 'Пікір жазыңыз...',
    send: 'Жіберу',
    reply: 'Жауап беру',
    commentsDisabled: 'Пікірлер өшірілген',
    deleteComment: 'Жою',
    adminPanel: 'Әкімші панелі',
    users: 'Пайдаланушылар',
    tests: 'Тесттер',
    statistics: 'Статистика',
    ban: 'Бұғаттау',
    unban: 'Бұғатты алу',
    warn: 'Ескерту',
    banned: 'Бұғатталған',
    role: 'Рөл',
    search: 'Іздеу',
    totalUsers: 'Барлық пайдаланушылар',
    totalTests: 'Барлық тесттер',
    totalResults: 'Барлық нәтижелер',
    bannedUsers: 'Бұғатталған',
    changeRole: 'Рөлді өзгерту',
    banUser: 'Пайдаланушыны бұғаттау',
    banReason: 'Бұғаттау себебі',
    warnMessage: 'Ескерту хабарламасы',
    recentUsers: 'Жаңа пайдаланушылар',
    recentTests: 'Жаңа тесттер',
    testResults: 'Тест нәтижелері',
    score: 'Ұпай',
    passed: 'Тапсырылды',
    failed: 'Тапсырылмады',
    viewResults: 'Нәтижелер',
    notifications: 'Хабарламалар',
    noNotifications: 'Хабарламалар жоқ',
    markAllRead: 'Барлығын оқылды деп белгілеу',
    report: 'Шағым',
    reportReason: 'Шағым себебі',
    reportSent: 'Шағым жіберілді',
    reportTest: 'Тестке шағымдану',
    reportComment: 'Пікірге шағымдану',
    reportUser: 'Пайдаланушыға шағымдану',
    editComment: 'Өңдеу',
    cancelEditConfirm: 'Өзгерістерді болдырмау керек пе?',
    edited: 'өңделген',
    testCreator: 'Автор',
    userProfile: 'Пайдаланушы профилі',
    testsCreated: 'Жасалған тесттер',
    testsTaken: 'Тапсырылған тесттер',
    exportCSV: 'CSV',
    exportJSON: 'JSON',
    exportPDF: 'PDF',
    draftFound: 'Жоба табылды',
    restoreDraft: 'Жобаны қалпына келтіру?',
    restore: 'Қалпына келтіру',
    discard: 'Жою',
    instantFeedback: 'Лездік тексеру',
    instantFeedbackDesc: 'Жауап бергеннен кейін дұрыс жауапты көрсетеді',
    correct: 'Дұрыс',
    incorrect: 'Қате',
    checkAnswer: 'Жауапты тексеру',
    explanation: 'Түсіндірме',
    // Passage
    addPassage: 'Оқу мәтінін қосу',
    hidePassage: 'Мәтінді жасыру',
    passage: 'Оқу мәтіні',
    passagePlaceholder: 'Сұрақтың үстінде көрсетілетін мәтін/үзіндіні енгізіңіз...',
    passageLabel: 'Мәтін',
    // Question types
    singleChoice: 'Бір жауап',
    multipleChoice: 'Бірнеше жауап',
    trueFalse: 'Дұрыс / Бұрыс',
    essay: 'Эссе',
    matching: 'Сәйкестендіру',
    fillBlank: 'Бос орынды толтыру',
    // True-false options
    optTrue: 'Дұрыс',
    optFalse: 'Бұрыс',
    optNotSure: 'Жауапқа сенімді емеспін',
    // CreateTest
    minOneQuestion: 'Кемінде 1 сұрақ',
    enterTestTitle: 'Тест атауын енгізіңіз',
    fillAllQuestions: 'Барлық сұрақтарды толтырыңыз',
    testUpdated: 'Тест жаңартылды!',
    testCreated: 'Тест құрылды!',
    errorSaving: 'Сақтау қатесі',
    mediaUploaded: 'Медиа жүктелді',
    errorUploadMedia: 'Медиа жүктеу қатесі',
    importedQuestions: 'Импортталған сұрақтар',
    cannotParseQuestions: 'Сұрақтарды тану мүмкін болмады. Форматты тексеріңіз.',
    errorReadingFile: 'Файлды оқу қатесі',
    errorLoadingBank: 'Банкті жүктеу қатесі',
    addedFromBank: 'Банктан сұрақтар қосылды',
    savedToBank: 'Сұрақтар банкке сақталды',
    errorSavingToBank: 'Банкке сақтау қатесі',
    deleteQuestion: 'Сұрақты жою',
    deleteQuestionConfirm: '{{num}} сұрақты жою? Бұл әрекетті қайтару мүмкін емес.',
    navigation: 'Навигация',
    questionsCount: 'Сұрақтар',
    pointsCount: 'Ұпайлар',
    fromQuestionBank: 'Сұрақ банкінен',
    importCSV: 'CSV импорт',
    saveToBank: 'Банкке сақтау',
    aiGenerate: 'AI Генерация',
    aiGenerateDesc: 'Мәтін немесе суреттен сұрақтар құру',
    aiTextInput: 'Мәтін',
    aiTextPlaceholder: 'Мәтін, конспект немесе кез-келген материалды қойыңыз...',
    aiImageInput: 'Сурет (скриншот, оқулық беті)',
    aiUploadImage: 'Сурет жүктеу',
    aiQuestionCount: 'Сұрақ саны',
    aiQuestionTypes: 'Сұрақ түрлері',
    aiGenerateBtn: 'Генерациялау',
    aiGenerating: 'Генерация...',
    aiPoweredBy: 'Azure OpenAI',
    aiProvideContent: 'Мәтін енгізіңіз немесе сурет жүктеңіз',
    aiNoQuestions: 'AI сұрақтар қайтармады. Қайта көріңіз.',
    aiFileTooLarge: 'Файл тым үлкен (макс 10МБ)',
    aiQuestionsAdded: '{{count}} сұрақ қосылды!',
    editTest: 'Тестті өңдеу',
    settings: 'Баптаулар',
    update: 'Жаңарту',
    testSettings: 'Тест баптаулары',
    timeLimitMin: 'Уақыт шегі (мин)',
    maxAttempts: 'Макс. әрекеттер',
    maxViolations: 'Макс. бұзушылықтар',
    isPublic: 'Жалпыға қолжетімді',
    shuffleQuestions: 'Сұрақтарды араластыру',
    shuffleOptions: 'Жауаптарды араластыру',
    showResults: 'Нәтижелерді көрсету',
    blockTabSwitch: 'Қойындыларды блоктау',
    blockCopyPaste: 'Көшіруді блоктау',
    blockScreenshot: 'Скриншотты блоктау',
    testTitlePlaceholder: 'Тест атауы...',
    testDescPlaceholder: 'Тест сипаттамасы (міндетті емес)...',
    newQuestion: 'Жаңа сұрақ...',
    questionTextPlaceholder: 'Сұрақ мәтіні...',
    addMedia: 'Медиа қосу (фото, видео, аудио)',
    optionPlaceholder: 'Нұсқа',
    addOption: 'Нұсқа қосу',
    essayHint: 'Студент толық жауап жазады. Оқытушы қолмен тексереді.',
    correctAnswer: 'Дұрыс жауап',
    enterCorrectAnswer: 'Дұрыс жауапты енгізіңіз',
    element: 'Элемент',
    pair: 'Жұп',
    addPair: 'Жұп қосу',
    explanationPlaceholder: 'Жауапқа түсіндірме (міндетті емес)...',
    addQuestion: 'Сұрақ қосу',
    updateTest: 'Тестті жаңарту',
    saveTest: 'Тестті сақтау',
    importFromCSV: 'CSV-ден импорт',
    clickToSelectFile: 'Файлды таңдау үшін басыңыз',
    questionBankTitle: 'Сұрақ банкі',
    bankEmpty: 'Банк бос. Мұнда көріну үшін тесттен сұрақтарды сақтаңыз.',
    selectQuestions: 'Сұрақтарды таңдаңыз',
    addSelected: 'Таңдалғандарды қосу',
    close: 'Жабу',
    points: 'ұпай',
    savingDraft: 'Сақтау...',
    draftSaved: 'Жоба сақталды',
    noLimitPlaceholder: '0 = шексіз',
    startDate: 'Басталу күні',
    endDate: 'Аяқталу күні',
    questionPoolSize: 'Пулдан сұрақтар',
    poolSizeHint: '0 = барлық сұрақтар',
    inactivityTimeout: 'Белсенділік тоқтау (мин)',
    inactivityHint: '0 = өшірілген',
    practiceMode: 'Жаттығу режимі',
    practiceModeDesc: 'Жаттығу — шексіз әрекеттер, нәтижелер сақталмайды',
    practiceModeLabel: 'Жаттығу',
    partialCredit: 'Жартылай балл',
    partialCreditDesc: 'Жартылай дұрыс жауаптар үшін жартылай балл беру (көп таңдау/сәйкестендіру)',
    changeTicket: 'Билетті ауыстыру',
    ticketHintPublic: 'Кез келген билетті таңдаңыз. Барлық билеттер барлығына қолжетімді.',
    aiHistory: 'Тарих',
    aiNoHistory: 'Генерация тарихы бос',
    clearAll: 'Барлығын тазалау',
    exportJSON: 'JSON экспорт',
    importJSON: 'JSON импорт',
    exportSuccess: 'Тест экспортталды!',
    importSuccess: 'Тест импортталды!',
    importError: 'Импорт қатесі — файл дұрыс емес',
    preview: 'Алдын ала қарау',
    previewMode: 'Алдын ала қарау — нәтиже сақталмайды',
    inactivityWarning: 'Сіз әлі мұндасыз ба?',
    inactivityCountdownMsg: 'Тест {{seconds}} сек ішінде автоматты аяқталады',
    imHere: 'Мен мұндамын!',
    category: 'Санат',
    allCategories: 'Барлық санаттар',
    // Ticket system
    ticketN: 'Билет #{{n}}',
    chooseTicket: 'Билетті таңдаңыз',
    ticketReady: 'Билет сіздікі. Бастау батырмасын басыңыз!',
    claimingTicket: 'Билет таңдалуда...',
    ticketHint: 'Жасыл — бос, Қызыл — бос емес. Тезірек таңдаңыз!',
    variantsEnabled: 'Билет/вариант жүйесі',
    variantCount: 'Вариант саны',
    variantsHint: 'Әр оқушы бірегей билет алады, сұрақтар аралас болады',
    // TakeTest
    matchingHint: 'Сол жақтағы элементті, содан кейін оң жақтағы жұбын басыңыз. Сәйкес жұптар бірдей түспен ерекшеленеді.',
    elements: 'Элементтер',
    pairs: 'Жұптар',
    yourPairs: 'Сіздің жұптарыңыз:',
    violationLimitExceeded: 'Бұзушылық шегі асылды! Тест автоматты түрде аяқталды.',
    timeUp: 'Уақыт бітті!',
    testNotFound: 'Тест табылмады',
    enterYourName: 'Атыңызды енгізіңіз',
    errorCheckingAnswer: 'Жауапты тексеру қатесі',
    errorSubmitting: 'Жіберу қатесі',
    point: 'ұпай',
    multipleAnswersHint: 'Бірнеше нұсқаны таңдауға болады',
    checking: 'Тексеруде...',
    writeYourAnswer: 'Жауабыңызды жазыңыз...',
    essayCheckedByTeacher: 'Эссе аяқтағаннан кейін оқытушы тексереді',
    enterAnswer: 'Жауабыңызды енгізіңіз...',
    correctAnswerIs: 'Дұрыс жауап',
    explanationLabel: 'Түсіндірме:',
    correctBanner: 'Дұрыс!',
    incorrectBanner: 'Қате',
    outOfPoints: '/',
    finishTest: 'Аяқтау',
    finishTestTitle: 'Тестті аяқтау',
    finishTestMessage: 'Сіз {{total}} сұрақтың {{answered}} жауап бердіңіз. Тестті аяқтап, жауаптарды жіберу керек пе?',
    finishBtn: 'Аяқтау',
    continueTest: 'Тестті жалғастыру',
    startTestBtn: 'Тестті бастау',
    yourName: 'Сіздің атыңыз',
    enterFullName: 'Толық атыңызды енгізіңіз',
    attempts: 'Әрекеттер',
    allAttemptsUsed: 'Барлық әрекеттер пайдаланылды',
    testRules: 'Тест ережелері:',
    ruleNoLeave: 'Тест бетінен шығуға болмайды (қойындыларды ауыстыру, браузерді кішірейту)',
    ruleViolationsTracked: 'Әр бұзушылық тіркеледі және оқытушыға көрінеді',
    ruleMaxViolations: 'Максимум бұзушылықтар: {{max}} — содан кейін тест автоматты түрде аяқталады',
    modeInstantFeedback: 'Режим: Лездік тексеру',
    instantFeedbackInfo: 'Әр жауаптан кейін оның дұрыс екенін бірден көресіз. Тексергеннен кейін жауапты өзгертуге болмайды.',
    answered: 'жауап берілді',
    selectOption: 'тандау',
    navigation: 'навигация',
    violation: 'Бұзушылық!',
    violationCount: 'Бұзушылық {{current}} / {{max}}',
    understood: 'Түсінікті',
    next: 'Келесі',
    prev: 'Артқа',
    // TestProfile
    questionTypes: 'Сұрақ түрлері',
    rateTest: 'Тестті бағалаңыз',
    yourRating: 'Сіздің бағаңыз',
    clickToRate: 'Бағалау үшін басыңыз',
    loginToRate: 'Тестті бағалау үшін кіріңіз',
    ratingUpdated: 'Баға жаңартылды',
    thanksForRating: 'Бағалағаныңыз үшін рахмет!',
    tabSwitchBlocked: 'Қойындыларды ауыстыру тыйым салынған. Макс. бұзушылықтар',
    allAttemptsUsedFull: 'Сіз барлық әрекеттерді пайдаландыңыз',
    viewAll: 'Барлығы →',
    min: 'мин',
    // Validation
    noCorrectAnswer: '{{num}} сұрақ: дұрыс жауапты белгілеңіз',
    emptyOptions: '{{num}} сұрақ: барлық жауап нұсқаларын толтырыңыз',
    // Dashboard
    errorLoadingTests: 'Тесттерді жүктеу қатесі',
    testDeleted: 'Тест жойылды',
    errorDeleting: 'Жою қатесі',
    deleteTestTitle: 'Тестті жою',
    deleteTestMsg: 'Бұл тестті жоюды қалайсыз ба? Барлық нәтижелер де жойылады.',
  }
};

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('unitest_lang');
    if (saved && ['en', 'ru', 'kz'].includes(saved)) return saved;
    return 'en';
  });

  useEffect(() => {
    localStorage.setItem('unitest_lang', lang);
  }, [lang]);

  const t = useCallback((key, params) => {
    let text = translations[lang]?.[key] || translations.en[key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(new RegExp(`\\{\\{${k}\\}\\}`, 'g'), v);
      });
    }
    return text;
  }, [lang]);

  const setLanguage = useCallback((newLang) => {
    if (['en', 'ru', 'kz'].includes(newLang)) {
      setLang(newLang);
    }
  }, []);

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
