import { createContext, useContext, useState, useEffect, useCallback } from 'react';

const translations = {
  en: {
    // Navbar
    home: 'Home',
    myTests: 'My Tests',
    results: 'Results',
    questionBank: 'Question Bank',
    createTest: 'Create Test',
    profile: 'Profile',
    admin: 'Admin',
    logout: 'Log out',
    teacher: 'Teacher',
    student: 'Student',
    adminRole: 'Admin',
    lightTheme: 'Light theme',
    darkTheme: 'Dark theme',
    // Dashboard
    welcome: 'Welcome',
    dashboardSubtitle: 'Access knowledge and track your progress',
    searchTests: 'Search tests...',
    newest: 'Newest',
    popular: 'Popular',
    rating: 'Rating',
    noTests: 'No tests yet',
    createFirst: 'Create your first test right now',
    publicTest: 'Public',
    privateTest: 'Private',
    questions: 'questions',
    noDescription: 'No description',
    deleteTest: 'Delete test',
    deleteTestConfirm: 'Delete this test? All results will also be deleted.',
    delete: 'Delete',
    edit: 'Edit',
    copyLink: 'Copy link',
    linkCopied: 'Link copied!',
    // Leaderboard
    leaderboard: 'Rating',
    totalParticipants: 'Total participants',
    emptyLeaderboard: 'Empty yet',
    noOneCompleted: 'No one has taken this test yet',
    error: 'Error',
    toHome: 'To home',
    // Auth
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    firstName: 'First name',
    lastName: 'Last name',
    middleName: 'Middle name',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    loginBtn: 'Log in',
    registerBtn: 'Register',
    // Profile
    profileTitle: 'Profile',
    editProfile: 'Edit profile',
    changePassword: 'Change password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    save: 'Save',
    cancel: 'Cancel',
    language: 'Language',
    uploadAvatar: 'Upload avatar',
    warnings: 'Warnings',
    memberSince: 'Member since',
    // General
    loading: 'Loading...',
    errorLoading: 'Loading error',
    back: 'Back',
    // Test
    startTest: 'Start Test',
    submitTest: 'Submit',
    nextQuestion: 'Next',
    prevQuestion: 'Previous',
    timeLeft: 'Time left',
    question: 'Question',
    of: 'of',
    // Comments
    comments: 'Comments',
    addComment: 'Add comment',
    writeComment: 'Write a comment...',
    send: 'Send',
    reply: 'Reply',
    commentsDisabled: 'Comments are disabled',
    deleteComment: 'Delete',
    // Admin
    adminPanel: 'Admin Panel',
    users: 'Users',
    tests: 'Tests',
    statistics: 'Statistics',
    ban: 'Ban',
    unban: 'Unban',
    warn: 'Warn',
    banned: 'Banned',
    role: 'Role',
    search: 'Search',
    totalUsers: 'Total users',
    totalTests: 'Total tests',
    totalResults: 'Total results',
    bannedUsers: 'Banned users',
    changeRole: 'Change role',
    banUser: 'Ban user',
    banReason: 'Ban reason',
    warnMessage: 'Warning message',
    recentUsers: 'Recent users',
    recentTests: 'Recent tests',
    // Results
    testResults: 'Test Results',
    score: 'Score',
    passed: 'Passed',
    failed: 'Failed',
    viewResults: 'View Results',
    // Notifications
    notifications: 'Notifications',
    noNotifications: 'No notifications',
    markAllRead: 'Mark all as read',
    // Reports
    report: 'Report',
    reportReason: 'Reason for report',
    reportSent: 'Report sent',
    reportTest: 'Report test',
    reportComment: 'Report comment',
    reportUser: 'Report user',
    // Comments extended
    editComment: 'Edit',
    edited: 'edited',
    testCreator: 'Author',
    // User profile
    userProfile: 'User Profile',
    testsCreated: 'Tests created',
    testsTaken: 'Tests taken',
    // Export
    exportCSV: 'CSV',
    exportJSON: 'JSON',
    exportPDF: 'PDF',
    // Auto-save
    draftFound: 'Draft found',
    restoreDraft: 'Restore draft?',
    restore: 'Restore',
    discard: 'Discard',
    instantFeedback: 'Instant check',
    instantFeedbackDesc: 'Shows the correct answer immediately after answering',
    correct: 'Correct',
    incorrect: 'Incorrect',
    checkAnswer: 'Check answer',
    explanation: 'Explanation',
    // Additional translations
    point: 'point',
    points: 'points',
    multipleAnswers: 'Multiple answers',
    contextTextLabel: 'General text for all questions',
    contextTextOptional: '(optional)',
    insertToAllQuestions: 'Insert to all questions',
    enterAnswer: 'Enter answer...',
    enterCorrectAnswer: 'Enter correct answer',
    selectQuestions: 'Select questions',
    enterTestName: 'Enter test name',
    enterYourName: 'Enter your name',
    enterFullName: 'Enter your full name',
    yourName: 'Your name',
    startTestBtn: 'Start test',
    finishTest: 'Finish test',
    continueTest: 'Continue test',
    testNotFound: 'Test not found',
    timeUp: 'Time is up!',
    checkAnswerError: 'Answer check error',
    submitError: 'Submit error',
    minutes: 'min',
    attempts: 'Attempts',
    matchingInstruction: 'Click an element on the left, then its pair on the right. Matched pairs will be highlighted with the same color.',
    elements: 'Elements',
    pairs: 'Pairs',
    yourPairs: 'Your pairs:',
    violationsLimit: 'Violations limit exceeded! Test automatically terminated.',
    testRules: 'Test rules:',
    instantFeedbackMode: 'Mode: Instant feedback',
    instantFeedbackInfo: 'After each answer, you will immediately see if it is correct. You cannot change the answer after checking.',
    maxViolations: 'Maximum violations',
    autoTerminate: '— after that the test will end automatically',
    allAttemptsUsed: 'You have already used all attempts',
    answeredQuestions: 'You answered',
    outOfQuestions: 'out of',
    questionsText: 'questions',
    rule1: '-- Do not leave the test page (switch tabs, minimize browser)',
    rule2: '-- Each violation is recorded and visible to the teacher',
    finishAndSubmit: 'Finish test and submit answers?',
    finish: 'Finish',
    fillAllQuestions: 'Fill in all questions',
    noCorrectAnswer: 'Question has no correct answer marked',
    noCorrectAnswerFound: 'Question has no correct answer',
    emptyOptions: 'Question has empty options',
    previous: 'Previous',
    next: 'Next',
    answered: 'answered',
  },
  ru: {
    home: 'Главная',
    myTests: 'Мои тесты',
    results: 'Результаты',
    questionBank: 'Банк вопросов',
    createTest: 'Создать тест',
    profile: 'Профиль',
    admin: 'Админ',
    logout: 'Выйти',
    teacher: 'Преподаватель',
    student: 'Студент',
    adminRole: 'Админ',
    lightTheme: 'Светлая тема',
    darkTheme: 'Тёмная тема',
    welcome: 'Добро пожаловать',
    dashboardSubtitle: 'Откройте доступ к знаниям и отслеживайте результаты',
    searchTests: 'Поиск тестов...',
    newest: 'Новые',
    popular: 'Популярные',
    rating: 'Рейтинг',
    noTests: 'Тестов пока нет',
    createFirst: 'Создайте свой первый тест прямо сейчас',
    publicTest: 'Публичный',
    privateTest: 'Приватный',
    questions: 'вопросов',
    noDescription: 'Без описания',
    deleteTest: 'Удалить тест',
    deleteTestConfirm: 'Удалить этот тест? Все результаты также будут удалены.',
    delete: 'Удалить',
    edit: 'Редактировать',
    copyLink: 'Скопировать ссылку',
    linkCopied: 'Ссылка скопирована!',
    leaderboard: 'Рейтинг',
    totalParticipants: 'Всего участников',
    emptyLeaderboard: 'Пока пусто',
    noOneCompleted: 'Никто ещё не прошёл этот тест',
    error: 'Ошибка',
    toHome: 'На главную',
    login: 'Вход',
    register: 'Регистрация',
    email: 'Email',
    password: 'Пароль',
    firstName: 'Имя',
    lastName: 'Фамилия',
    middleName: 'Отчество',
    noAccount: 'Нет аккаунта?',
    haveAccount: 'Уже есть аккаунт?',
    loginBtn: 'Войти',
    registerBtn: 'Зарегистрироваться',
    profileTitle: 'Профиль',
    editProfile: 'Редактировать профиль',
    changePassword: 'Изменить пароль',
    currentPassword: 'Текущий пароль',
    newPassword: 'Новый пароль',
    save: 'Сохранить',
    cancel: 'Отмена',
    language: 'Язык',
    uploadAvatar: 'Загрузить аватар',
    warnings: 'Предупреждения',
    memberSince: 'Участник с',
    loading: 'Загрузка...',
    errorLoading: 'Ошибка загрузки',
    back: 'Назад',
    startTest: 'Начать тест',
    submitTest: 'Отправить',
    nextQuestion: 'Далее',
    prevQuestion: 'Назад',
    timeLeft: 'Осталось',
    question: 'Вопрос',
    of: 'из',
    comments: 'Комментарии',
    addComment: 'Добавить комментарий',
    writeComment: 'Напишите комментарий...',
    send: 'Отправить',
    reply: 'Ответить',
    commentsDisabled: 'Комментарии отключены',
    deleteComment: 'Удалить',
    adminPanel: 'Панель администратора',
    users: 'Пользователи',
    tests: 'Тесты',
    statistics: 'Статистика',
    ban: 'Заблокировать',
    unban: 'Разблокировать',
    warn: 'Предупредить',
    banned: 'Заблокирован',
    role: 'Роль',
    search: 'Поиск',
    totalUsers: 'Всего пользователей',
    totalTests: 'Всего тестов',
    totalResults: 'Всего результатов',
    bannedUsers: 'Заблокировано',
    changeRole: 'Изменить роль',
    banUser: 'Заблокировать пользователя',
    banReason: 'Причина блокировки',
    warnMessage: 'Сообщение предупреждения',
    recentUsers: 'Новые пользователи',
    recentTests: 'Новые тесты',
    testResults: 'Результаты теста',
    score: 'Баллы',
    passed: 'Сдано',
    failed: 'Не сдано',
    viewResults: 'Результаты',
    notifications: 'Уведомления',
    noNotifications: 'Нет уведомлений',
    markAllRead: 'Прочитать все',
    report: 'Пожаловаться',
    reportReason: 'Причина жалобы',
    reportSent: 'Жалоба отправлена',
    reportTest: 'Пожаловаться на тест',
    reportComment: 'Пожаловаться на комментарий',
    reportUser: 'Пожаловаться на пользователя',
    editComment: 'Редактировать',
    edited: 'изменено',
    testCreator: 'Автор',
    userProfile: 'Профиль пользователя',
    testsCreated: 'Тестов создано',
    testsTaken: 'Тестов пройдено',
    exportCSV: 'CSV',
    exportJSON: 'JSON',
    exportPDF: 'PDF',
    draftFound: 'Найден черновик',
    restoreDraft: 'Восстановить черновик?',
    restore: 'Восстановить',
    discard: 'Удалить',
    instantFeedback: 'Мгновенная проверка',
    instantFeedbackDesc: 'Показывает правильный ответ сразу после ответа',
    correct: 'Правильно',
    incorrect: 'Неправильно',
    checkAnswer: 'Проверить ответ',
    explanation: 'Пояснение',
    // Additional translations
    point: 'балл',
    points: 'баллов',
    multipleAnswers: 'Несколько ответов',
    contextTextLabel: 'Общий текст для всех вопросов',
    contextTextOptional: '(необязательно)',
    insertToAllQuestions: 'Вставить во все вопросы',
    enterAnswer: 'Введите ответ...',
    enterCorrectAnswer: 'Введите правильный ответ',
    selectQuestions: 'Выберите вопросы',
    enterTestName: 'Введите название теста',
    enterYourName: 'Введите ваше имя',
    enterFullName: 'Введите ваше полное имя',
    yourName: 'Ваше имя',
    startTestBtn: 'Начать тест',
    finishTest: 'Завершить тест',
    continueTest: 'Продолжить тест',
    testNotFound: 'Тест не найден',
    timeUp: 'Время вышло!',
    checkAnswerError: 'Ошибка проверки ответа',
    submitError: 'Ошибка отправки',
    minutes: 'мин',
    attempts: 'Попытки',
    matchingInstruction: 'Нажмите на элемент слева, затем на его пару справа. Совпавшие пары будут выделены одним цветом.',
    elements: 'Элементы',
    pairs: 'Пары',
    yourPairs: 'Ваши пары:',
    violationsLimit: 'Превышен лимит нарушений! Тест автоматически завершён.',
    testRules: 'Правила прохождения теста:',
    instantFeedbackMode: 'Режим: Мгновенная проверка',
    instantFeedbackInfo: 'После каждого ответа вы сразу увидите, правильный ли он. Изменить ответ после проверки нельзя.',
    maxViolations: 'Максимум нарушений',
    autoTerminate: '— после этого тест завершится автоматически',
    allAttemptsUsed: 'Вы уже использовали все попытки',
    answeredQuestions: 'Вы ответили на',
    outOfQuestions: 'из',
    questionsText: 'вопросов',
    rule1: '-- Нельзя покидать страницу теста (переключать вкладки, сворачивать браузер)',
    rule2: '-- Каждое нарушение фиксируется и видно преподавателю',
    finishAndSubmit: 'Завершить тест и отправить ответы?',
    finish: 'Завершить',
    fillAllQuestions: 'Заполните все вопросы',
    noCorrectAnswer: 'В вопросе не отмечен правильный ответ',
    noCorrectAnswerFound: 'В вопросе нет правильного ответа',
    emptyOptions: 'В вопросе есть пустые варианты',
    previous: 'Назад',
    next: 'Далее',
    answered: 'отвечено',
  },
  kz: {
    home: 'Басты',
    myTests: 'Менің тесттерім',
    results: 'Нәтижелер',
    questionBank: 'Сұрақ банкі',
    createTest: 'Тест құру',
    profile: 'Профиль',
    admin: 'Админ',
    logout: 'Шығу',
    teacher: 'Оқытушы',
    student: 'Студент',
    adminRole: 'Админ',
    lightTheme: 'Жарық тақырып',
    darkTheme: 'Қараңғы тақырып',
    welcome: 'Қош келдіңіз',
    dashboardSubtitle: 'Білімге қол жеткізіңіз және нәтижелерді қадағалаңыз',
    searchTests: 'Тесттерді іздеу...',
    newest: 'Жаңа',
    popular: 'Танымал',
    rating: 'Рейтинг',
    noTests: 'Тесттер жоқ',
    createFirst: 'Бірінші тестіңізді қазір жасаңыз',
    publicTest: 'Жалпыға қолжетімді',
    privateTest: 'Жеке',
    questions: 'сұрақ',
    noDescription: 'Сипаттама жоқ',
    deleteTest: 'Тестті жою',
    deleteTestConfirm: 'Бұл тестті жоюды қалайсыз ба? Барлық нәтижелер де жойылады.',
    delete: 'Жою',
    edit: 'Өңдеу',
    copyLink: 'Сілтемені көшіру',
    linkCopied: 'Сілтеме көшірілді!',
    leaderboard: 'Рейтинг',
    totalParticipants: 'Барлық қатысушылар',
    emptyLeaderboard: 'Әзірге бос',
    noOneCompleted: 'Бұл тестті әлі ешкім тапсырмаған',
    error: 'Қате',
    toHome: 'Басты бетке',
    login: 'Кіру',
    register: 'Тіркелу',
    email: 'Email',
    password: 'Құпия сөз',
    firstName: 'Аты',
    lastName: 'Тегі',
    middleName: 'Әкесінің аты',
    noAccount: 'Аккаунтыңыз жоқ па?',
    haveAccount: 'Аккаунтыңыз бар ма?',
    loginBtn: 'Кіру',
    registerBtn: 'Тіркелу',
    profileTitle: 'Профиль',
    editProfile: 'Профильді өңдеу',
    changePassword: 'Құпия сөзді өзгерту',
    currentPassword: 'Ағымдағы құпия сөз',
    newPassword: 'Жаңа құпия сөз',
    save: 'Сақтау',
    cancel: 'Бас тарту',
    language: 'Тіл',
    uploadAvatar: 'Аватар жүктеу',
    warnings: 'Ескертулер',
    memberSince: 'Мүше болған уақыт',
    loading: 'Жүктелуде...',
    errorLoading: 'Жүктеу қатесі',
    back: 'Артқа',
    startTest: 'Тестті бастау',
    submitTest: 'Жіберу',
    nextQuestion: 'Келесі',
    prevQuestion: 'Алдыңғы',
    timeLeft: 'Қалған уақыт',
    question: 'Сұрақ',
    of: '/',
    comments: 'Пікірлер',
    addComment: 'Пікір қосу',
    writeComment: 'Пікір жазыңыз...',
    send: 'Жіберу',
    reply: 'Жауап беру',
    commentsDisabled: 'Пікірлер өшірілген',
    deleteComment: 'Жою',
    adminPanel: 'Әкімші панелі',
    users: 'Пайдаланушылар',
    tests: 'Тесттер',
    statistics: 'Статистика',
    ban: 'Бұғаттау',
    unban: 'Бұғатты алу',
    warn: 'Ескерту',
    banned: 'Бұғатталған',
    role: 'Рөл',
    search: 'Іздеу',
    totalUsers: 'Барлық пайдаланушылар',
    totalTests: 'Барлық тесттер',
    totalResults: 'Барлық нәтижелер',
    bannedUsers: 'Бұғатталған',
    changeRole: 'Рөлді өзгерту',
    banUser: 'Пайдаланушыны бұғаттау',
    banReason: 'Бұғаттау себебі',
    warnMessage: 'Ескерту хабарламасы',
    recentUsers: 'Жаңа пайдаланушылар',
    recentTests: 'Жаңа тесттер',
    testResults: 'Тест нәтижелері',
    score: 'Ұпай',
    passed: 'Тапсырылды',
    failed: 'Тапсырылмады',
    viewResults: 'Нәтижелер',
    notifications: 'Хабарламалар',
    noNotifications: 'Хабарламалар жоқ',
    markAllRead: 'Барлығын оқылды деп белгілеу',
    report: 'Шағым',
    reportReason: 'Шағым себебі',
    reportSent: 'Шағым жіберілді',
    reportTest: 'Тестке шағымдану',
    reportComment: 'Пікірге шағымдану',
    reportUser: 'Пайдаланушыға шағымдану',
    editComment: 'Өңдеу',
    edited: 'өңделген',
    testCreator: 'Автор',
    userProfile: 'Пайдаланушы профилі',
    testsCreated: 'Жасалған тесттер',
    testsTaken: 'Тапсырылған тесттер',
    exportCSV: 'CSV',
    exportJSON: 'JSON',
    exportPDF: 'PDF',
    draftFound: 'Жоба табылды',
    restoreDraft: 'Жобаны қалпына келтіру?',
    restore: 'Қалпына келтіру',
    discard: 'Жою',
    instantFeedback: 'Лездік тексеру',
    instantFeedbackDesc: 'Жауап бергеннен кейін дұрыс жауапты көрсетеді',
    correct: 'Дұрыс',
    incorrect: 'Қате',
    checkAnswer: 'Жауапты тексеру',
    explanation: 'Түсіндірме',
    // Additional translations
    point: 'ұпай',
    points: 'ұпай',
    multipleAnswers: 'Бірнеше жауап',
    contextTextLabel: 'Барлық сұрақтарға арналған жалпы мәтін',
    contextTextOptional: '(міндетті емес)',
    insertToAllQuestions: 'Барлық сұрақтарға қою',
    enterAnswer: 'Жауапты енгізіңіз...',
    enterCorrectAnswer: 'Дұрыс жауапты енгізіңіз',
    selectQuestions: 'Сұрақтарды таңдаңыз',
    enterTestName: 'Тест атауын енгізіңіз',
    enterYourName: 'Атыңызды енгізіңіз',
    enterFullName: 'Толық атыңызды енгізіңіз',
    yourName: 'Сіздің атыңыз',
    startTestBtn: 'Тестті бастау',
    finishTest: 'Тестті аяқтау',
    continueTest: 'Тестті жалғастыру',
    testNotFound: 'Тест табылмады',
    timeUp: 'Уақыт бітті!',
    checkAnswerError: 'Жауапты тексеру қатесі',
    submitError: 'Жіберу қатесі',
    minutes: 'мин',
    attempts: 'Әрекеттер',
    matchingInstruction: 'Сол жақтағы элементті, содан кейін оң жақтағы жұбын басыңыз. Сәйкес жұптар бірдей түспен ерекшеленеді.',
    elements: 'Элементтер',
    pairs: 'Жұптар',
    yourPairs: 'Сіздің жұптарыңыз:',
    violationsLimit: 'Бұзушылық шегі асып кетті! Тест автоматты түрде аяқталды.',
    testRules: 'Тестті өту ережелері:',
    instantFeedbackMode: 'Режим: Лездік тексеру',
    instantFeedbackInfo: 'Әрбір жауаптан кейін дұрыс екенін бірден көресіз. Тексеруден кейін жауапты өзгерту мүмкін емес.',
    maxViolations: 'Максималды бұзушылықтар',
    autoTerminate: '— содан кейін тест автоматты түрде аяқталады',
    allAttemptsUsed: 'Сіз барлық әрекеттерді пайдаландыңыз',
    answeredQuestions: 'Сіз жауап бердіңіз',
    outOfQuestions: '/',
    questionsText: 'сұрақ',
    rule1: '-- Тест бетінен шығуға болмайды (қойындыларды ауыстыру, браузерді кішірейту)',
    rule2: '-- Әрбір бұзушылық тіркеледі және оқытушыға көрінеді',
    finishAndSubmit: 'Тестті аяқтап, жауаптарды жіберу керек пе?',
    finish: 'Аяқтау',
    fillAllQuestions: 'Барлық сұрақтарды толтырыңыз',
    noCorrectAnswer: 'Сұрақта дұрыс жауап белгіленбеген',
    noCorrectAnswerFound: 'Сұрақта дұрыс жауап жоқ',
    emptyOptions: 'Сұрақта бос нұсқалар бар',
    previous: 'Артқа',
    next: 'Келесі',
    answered: 'жауап берілді',
  }
};

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('unitest_lang');
    if (saved && ['en', 'ru', 'kz'].includes(saved)) return saved;
    return 'en';
  });

  useEffect(() => {
    localStorage.setItem('unitest_lang', lang);
  }, [lang]);

  const t = useCallback((key) => {
    return translations[lang]?.[key] || translations.en[key] || key;
  }, [lang]);

  const setLanguage = useCallback((newLang) => {
    if (['en', 'ru', 'kz'].includes(newLang)) {
      setLang(newLang);
    }
  }, []);

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
