import { createContext, useContext, useState, useEffect, useCallback } from 'react';

const translations = {
  en: {
    landingBadge: 'The easiest way to test knowledge',
    landingHeroTitle: 'Assess with confidence,',
    landingHeroSubtitle: 'powered by AI',
    landingHeroDesc: 'UniTest is an all-in-one platform for educators to create tests, monitor students, and analyze results seamlessly.',
    landingStartBtn: 'Get Started Free',
    landingLoginBtn: 'Log in',
    landingFeaturesHeader: 'Everything you need to succeed',
    landingFeaturesSubHeader: 'Powerful tools designed specifically for modern educators and institutions.',
    landingFeatureAIGenTitle: 'AI Generation',
    landingFeatureAIGenDesc: 'Generate questions from text or documents instantly using AI.',
    landingFeatureLevelsTitle: 'Difficulty DNA',
    landingFeatureLevelsDesc: 'Dynamic 5-level difficulty system for precise knowledge assessment.',
    landingFeatureAnalyticsTitle: 'Deep Analytics',
    landingFeatureAnalyticsDesc: 'Track performance with real-time analytics and detailed score reports.',
    landingFeatureSecurityTitle: 'Anti-Cheat',
    landingFeatureSecurityDesc: 'Browser lock, tab tracking, and secure execution for honest testing.',
    landingStepsHeader: 'How it works',
    landingStepsSubHeader: 'Create your first test and get results in minutes.',
    landingStep1Title: 'Create',
    landingStep1Desc: 'Write or generate test questions in seconds.',
    landingStep2Title: 'Share',
    landingStep2Desc: 'Send a short link to your students or groups.',
    landingStep3Title: 'Analyze',
    landingStep3Desc: 'Review results and grade automatically.',
    landingCtaHeader: 'Ready to transform your teaching?',
    landingCtaDesc: 'Join thousands of educators who are already using UniTest.',
    landingCtaBtn: 'Create Free Account',

    // Navbar
    home: 'Home',
    myTests: 'My Tests',
    results: 'Results',
    questionBank: 'Question Bank',
    groups: 'Groups',
    createTest: 'Create Test',
    profile: 'Profile',
    admin: 'Admin',
    logout: 'Log out',
    teacher: 'Teacher',
    student: 'Student',
    adminRole: 'Admin',
    lightTheme: 'Light theme',
    darkTheme: 'Dark theme',
    // Dashboard
    welcome: 'Welcome',
    dashboardSubtitle: 'Access knowledge and track your progress',
    searchTests: 'Search tests...',
    newest: 'Newest',
    popular: 'Popular',
    rating: 'Rating',
    noTests: 'No tests yet',
    createFirst: 'Create your first test right now',
    publicTest: 'Public',
    privateTest: 'Private',
    questions: 'questions',
    noDescription: 'No description',
    deleteTest: 'Delete test',
    deleteTestConfirm: 'Delete this test? All results will also be deleted.',
    delete: 'Delete',
    edit: 'Edit',
    copyLink: 'Copy link',
    linkCopied: 'Link copied!',
    // Leaderboard
    leaderboard: 'Rating',
    totalParticipants: 'Total participants',
    emptyLeaderboard: 'Empty yet',
    noOneCompleted: 'No one has taken this test yet',
    error: 'Error',
    toHome: 'To home',
    // Auth
    login: 'Login',
    register: 'Register',
    email: 'Email',
    password: 'Password',
    firstName: 'First name',
    lastName: 'Last name',
    middleName: 'Middle name',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    loginBtn: 'Log in',
    registerBtn: 'Register',
    // Profile
    profileTitle: 'Profile',
    editProfile: 'Edit profile',
    changePassword: 'Change password',
    currentPassword: 'Current password',
    newPassword: 'New password',
    save: 'Save',
    cancel: 'Cancel',
    language: 'Language',
    uploadAvatar: 'Upload avatar',
    warnings: 'Warnings',
    memberSince: 'Member since',
    // General
    loading: 'Loading...',
    errorLoading: 'Loading error',
    back: 'Back',
    // Test
    startTest: 'Start Test',
    submitTest: 'Submit',
    nextQuestion: 'Next',
    prevQuestion: 'Previous',
    timeLeft: 'Time left',
    question: 'Question',
    of: 'of',
    // Comments
    comments: 'Comments',
    addComment: 'Add comment',
    writeComment: 'Write a comment...',
    send: 'Send',
    reply: 'Reply',
    commentsDisabled: 'Comments are disabled',
    deleteComment: 'Delete',
    // Admin
    adminPanel: 'Admin Panel',
    users: 'Users',
    tests: 'Tests',
    statistics: 'Statistics',
    ban: 'Ban',
    unban: 'Unban',
    warn: 'Warn',
    banned: 'Banned',
    role: 'Role',
    search: 'Search',
    totalUsers: 'Total users',
    totalTests: 'Total tests',
    totalResults: 'Total results',
    bannedUsers: 'Banned users',
    changeRole: 'Change role',
    banUser: 'Ban user',
    banReason: 'Ban reason',
    warnMessage: 'Warning message',
    recentUsers: 'Recent users',
    recentTests: 'Recent tests',
    // Results
    testResults: 'Test Results',
    score: 'Score',
    passed: 'Passed',
    failed: 'Failed',
    viewResults: 'View Results',
    // Notifications
    notifications: 'Notifications',
    noNotifications: 'No notifications',
    markAllRead: 'Mark all as read',
    // Reports
    report: 'Report',
    reportReason: 'Reason for report',
    reportSent: 'Report sent',
    reportTest: 'Report test',
    reportComment: 'Report comment',
    reportUser: 'Report user',
    // Comments extended
    editComment: 'Edit',
    cancelEditConfirm: 'Discard changes?',
    edited: 'edited',
    testCreator: 'Author',
    // User profile
    userProfile: 'User Profile',
    testsCreated: 'Tests created',
    testsTaken: 'Tests taken',
    // Export
    exportCSV: 'CSV',
    exportJSON: 'JSON',
    exportPDF: 'PDF',
    // Auto-save
    draftFound: 'Draft found',
    restoreDraft: 'Restore draft?',
    restore: 'Restore',
    discard: 'Discard',
    instantFeedback: 'Instant check',
    instantFeedbackDesc: 'Shows the correct answer immediately after answering',
    correct: 'Correct',
    incorrect: 'Incorrect',
    checkAnswer: 'Check answer',
    explanation: 'Explanation',
    // Passage
    addPassage: 'Add reading text',
    hidePassage: 'Hide reading text',
    passage: 'Reading text',
    passagePlaceholder: 'Enter a reading passage/text that will be shown above the question...',
    passageLabel: 'Text',
    // Question types
    singleChoice: 'Single answer',
    multipleChoice: 'Multiple answers',
    trueFalse: 'True / False',
    essay: 'Essay',
    matching: 'Matching',
    fillBlank: 'Fill in the blank',
    // True-false options
    optTrue: 'True',
    optFalse: 'False',
    optNotSure: 'Not sure',
    // CreateTest
    minOneQuestion: 'Minimum 1 question',
    enterTestTitle: 'Enter test title',
    fillAllQuestions: 'Fill in all questions',
    testUpdated: 'Test updated!',
    testCreated: 'Test created!',
    errorSaving: 'Error saving',
    mediaUploaded: 'Media uploaded',
    errorUploadMedia: 'Error uploading media',
    importedQuestions: 'Imported questions',
    cannotParseQuestions: 'Could not parse questions. Check the format.',
    errorReadingFile: 'Error reading file',
    errorLoadingBank: 'Error loading bank',
    addedFromBank: 'Added questions from bank',
    savedToBank: 'Questions saved to bank',
    errorSavingToBank: 'Error saving to bank',
    deleteQuestion: 'Delete question',
    deleteQuestionConfirm: 'Delete question #{{num}}? This action cannot be undone.',
    navigation: 'Navigation',
    questionsCount: 'Questions',
    pointsCount: 'Points',
    fromQuestionBank: 'From question bank',
    importCSV: 'Import CSV',
    saveToBank: 'Save to bank',
    aiGenerate: 'AI Generate',
    aiGenerateDesc: 'Create questions from text or image',
    aiTextInput: 'Text content',
    aiTextPlaceholder: 'Paste text, lecture notes, or any content to generate questions from...',
    aiImageInput: 'Image (screenshot, textbook page)',
    aiUploadImage: 'Upload image',
    aiQuestionCount: 'Questions',
    aiQuestionTypes: 'Question types',
    aiGenerateBtn: 'Generate',
    aiGenerating: 'Generating...',
    aiPoweredBy: 'Powered by Azure OpenAI',
    aiProvideContent: 'Provide text or upload an image',
    aiNoQuestions: 'AI returned no questions. Try again.',
    aiFileTooLarge: 'File too large (max 10MB)',
    aiQuestionsAdded: '{{count}} questions added!',
    editTest: 'Edit test',
    settings: 'Settings',
    update: 'Update',
    testSettings: 'Test settings',
    timeLimitMin: 'Time limit (min)',
    maxAttempts: 'Max attempts',
    maxViolations: 'Max violations',
    isPublic: 'Public',
    shuffleQuestions: 'Shuffle questions',
    shuffleOptions: 'Shuffle options',
    showResults: 'Show results',
    blockTabSwitch: 'Block tabs',
    blockCopyPaste: 'Block copy',
    blockScreenshot: 'Block screenshots',
    testTitlePlaceholder: 'Test title...',
    testDescPlaceholder: 'Test description (optional)...',
    newQuestion: 'New question...',
    questionTextPlaceholder: 'Question text...',
    addMedia: 'Add media (photo, video, audio)',
    optionPlaceholder: 'Option',
    addOption: 'Add option',
    essayHint: 'Student will write a detailed answer. Manually graded by teacher.',
    correctAnswer: 'Correct answer',
    enterCorrectAnswer: 'Enter correct answer',
    element: 'Element',
    pair: 'Pair',
    addPair: 'Add pair',
    explanationPlaceholder: 'Explanation for the answer (optional)...',
    addQuestion: 'Add question',
    updateTest: 'Update test',
    saveTest: 'Save test',
    importFromCSV: 'Import from CSV',
    clickToSelectFile: 'Click to select file',
    questionBankTitle: 'Question bank',
    bankEmpty: 'Bank is empty. Save questions from a test for them to appear here.',
    selectQuestions: 'Select questions',
    addSelected: 'Add selected',
    close: 'Close',
    points: 'points',
    savingDraft: 'Saving...',
    draftSaved: 'Draft saved',
    noLimitPlaceholder: '0 = no limit',
    startDate: 'Start date',
    endDate: 'End date',
    questionPoolSize: 'Questions from pool',
    poolSizeHint: '0 = all questions',
    inactivityTimeout: 'Inactivity timeout (min)',
    inactivityHint: '0 = disabled',
    practiceMode: 'Practice mode',
    practiceModeDesc: 'Training mode — unlimited attempts, results not saved',
    practiceModeLabel: 'Practice',
    partialCredit: 'Partial credit',
    partialCreditDesc: 'Award partial points for partially correct multiple-choice/matching answers',
    changeTicket: 'Change ticket',
    ticketHintPublic: 'Choose any ticket. Each ticket is available to everyone.',
    aiHistory: 'History',
    aiNoHistory: 'No generation history yet',
    clearAll: 'Clear all',
    exportJSON: 'Export JSON',
    importJSON: 'Import JSON',
    exportSuccess: 'Test exported!',
    importSuccess: 'Test imported!',
    importError: 'Import error — invalid file',
    preview: 'Preview',
    previewMode: 'Preview mode — results not saved',
    inactivityWarning: 'Are you still there?',
    inactivityCountdownMsg: 'Test will auto-submit in {{seconds}} sec',
    imHere: "I'm here!",
    category: 'Category',
    allCategories: 'All categories',
    // Ticket system
    ticketN: 'Ticket #{{n}}',
    chooseTicket: 'Choose your ticket',
    ticketReady: 'Your ticket is locked in. Press Start!',
    claimingTicket: 'Claiming ticket...',
    ticketHint: 'Green — available, Red — taken. Choose quickly!',
    variantsEnabled: 'Ticket/Variant System',
    variantCount: 'Number of variants',
    variantsHint: 'Each student gets a unique ticket with shuffled questions',
    // TakeTest
    matchingHint: 'Click an item on the left, then its pair on the right. Matched pairs are highlighted.',
    elements: 'Elements',
    pairs: 'Pairs',
    yourPairs: 'Your pairs:',
    violationLimitExceeded: 'Violation limit exceeded! Test auto-submitted.',
    timeUp: 'Time is up!',
    testNotFound: 'Test not found',
    enterYourName: 'Enter your name',
    errorCheckingAnswer: 'Error checking answer',
    errorSubmitting: 'Error submitting',
    point: 'point',
    multipleAnswersHint: 'You can select multiple options',
    checking: 'Checking...',
    writeYourAnswer: 'Write your answer...',
    essayCheckedByTeacher: 'Essay is checked by teacher after submission',
    enterAnswer: 'Enter answer...',
    correctAnswerIs: 'Correct answer',
    explanationLabel: 'Explanation:',
    correctBanner: 'Correct!',
    incorrectBanner: 'Incorrect',
    outOfPoints: 'out of',
    finishTest: 'Finish test',
    finishTestTitle: 'Finish test',
    finishTestMessage: 'You answered {{answered}} of {{total}} questions. Finish and submit answers?',
    finishBtn: 'Finish',
    continueTest: 'Continue test',
    startTestBtn: 'Start test',
    yourName: 'Your name',
    enterFullName: 'Enter your full name',
    attempts: 'Attempts',
    allAttemptsUsed: 'All attempts used',
    testRules: 'Test rules:',
    ruleNoLeave: 'You cannot leave the test page (switch tabs, minimize browser)',
    ruleViolationsTracked: 'Each violation is recorded and visible to the teacher',
    ruleMaxViolations: 'Max violations: {{max}} — after that the test ends automatically',
    modeInstantFeedback: 'Mode: Instant check',
    instantFeedbackInfo: 'After each answer you will see if it is correct. You cannot change the answer after checking.',
    answered: 'answered',
    selectOption: 'select',
    navigation: 'navigate',
    violation: 'Violation!',
    violationCount: 'Violation {{current}} of {{max}}',
    understood: 'Understood',
    next: 'Next',
    prev: 'Back',
    // TestProfile
    questionTypes: 'Question types',
    rateTest: 'Rate this test',
    yourRating: 'Your rating',
    clickToRate: 'Click to rate',
    loginToRate: 'Log in to rate the test',
    ratingUpdated: 'Rating updated',
    thanksForRating: 'Thanks for rating!',
    tabSwitchBlocked: 'Tab switching is blocked. Max violations',
    allAttemptsUsedFull: 'You have used all attempts',
    viewAll: 'All →',
    min: 'min',
    // Validation
    noCorrectAnswer: 'Question {{num}}: mark the correct answer',
    emptyOptions: 'Question {{num}}: fill in all answer options',
    // Dashboard
    errorLoadingTests: 'Error loading tests',
    testDeleted: 'Test deleted',
    errorDeleting: 'Error deleting',
    deleteTestTitle: 'Delete test',
    deleteTestMsg: 'Delete this test? All results will also be deleted.',
  },
  ru: {
    landingBadge: 'Самый простой способ проверить знания',
    landingHeroTitle: 'Оценивайте уверенно,',
    landingHeroSubtitle: 'с помощью ИИ',
    landingHeroDesc: 'UniTest — это комплексная платформа для преподавателей: создавайте тесты, отслеживайте студентов и анализируйте результаты.',
    landingStartBtn: 'Начать бесплатно',
    landingLoginBtn: 'Войти',
    landingFeaturesHeader: 'Всё необходимое для успеха',
    landingFeaturesSubHeader: 'Мощные инструменты, созданные специально для современных преподавателей и учебных заведений.',
    landingFeatureAIGenTitle: 'Генерация с ИИ',
    landingFeatureAIGenDesc: 'Создавайте вопросы из текста или документов в мгновение ока с помощью ИИ.',
    landingFeatureLevelsTitle: 'ДНК Сложности',
    landingFeatureLevelsDesc: 'Динамическая 5-уровневая система сложности для точной оценки знаний.',
    landingFeatureAnalyticsTitle: 'Глубокая аналитика',
    landingFeatureAnalyticsDesc: 'Отслеживайте успеваемость с помощью аналитики в реальном времени и подробных отчетов.',
    landingFeatureSecurityTitle: 'Античит',
    landingFeatureSecurityDesc: 'Блокировка браузера, прозрачность вкладок и безопасная проверка для честного тестирования.',
    landingStepsHeader: 'Как это работает',
    landingStepsSubHeader: 'Создайте свой первый тест и получите результаты за считанные минуты.',
    landingStep1Title: 'Создайте',
    landingStep1Desc: 'Напишите или сгенерируйте вопросы теста за секунды.',
    landingStep2Title: 'Поделитесь',
    landingStep2Desc: 'Отправьте короткую ссылку студентам или группам.',
    landingStep3Title: 'Проанализируйте',
    landingStep3Desc: 'Просматривайте результаты и оценивайте автоматически.',
    landingCtaHeader: 'Готовы трансформировать обучение?',
    landingCtaDesc: 'Присоединяйтесь к тысячам преподавателей, которые уже используют UniTest.',
    landingCtaBtn: 'Создать бесплатный аккаунт',

    home: 'Главная',
    myTests: 'Мои тесты',
    results: 'Результаты',
    questionBank: 'Банк вопросов',
    groups: 'Группы',
    createTest: 'Создать тест',
    profile: 'Профиль',
    admin: 'Админ',
    logout: 'Выйти',
    teacher: 'Преподаватель',
    student: 'Студент',
    adminRole: 'Админ',
    lightTheme: 'Светлая тема',
    darkTheme: 'Тёмная тема',
    welcome: 'Добро пожаловать',
    dashboardSubtitle: 'Откройте доступ к знаниям и отслеживайте результаты',
    searchTests: 'Поиск тестов...',
    newest: 'Новые',
    popular: 'Популярные',
    rating: 'Рейтинг',
    noTests: 'Тестов пока нет',
    createFirst: 'Создайте свой первый тест прямо сейчас',
    publicTest: 'Публичный',
    privateTest: 'Приватный',
    questions: 'вопросов',
    noDescription: 'Без описания',
    deleteTest: 'Удалить тест',
    deleteTestConfirm: 'Удалить этот тест? Все результаты также будут удалены.',
    delete: 'Удалить',
    edit: 'Редактировать',
    copyLink: 'Скопировать',
    linkCopied: 'Ссылка скопирована!',
    leaderboard: 'Рейтинг',
    totalParticipants: 'Всего участников',
    emptyLeaderboard: 'Пока пусто',
    noOneCompleted: 'Никто ещё не прошёл этот тест',
    error: 'Ошибка',
    toHome: 'На главную',
    login: 'Вход',
    register: 'Регистрация',
    email: 'Email',
    password: 'Пароль',
    firstName: 'Имя',
    lastName: 'Фамилия',
    middleName: 'Отчество',
    noAccount: 'Нет аккаунта?',
    haveAccount: 'Уже есть аккаунт?',
    loginBtn: 'Войти',
    registerBtn: 'Зарегистрироваться',
    profileTitle: 'Профиль',
    editProfile: 'Редактировать профиль',
    changePassword: 'Изменить пароль',
    currentPassword: 'Текущий пароль',
    newPassword: 'Новый пароль',
    save: 'Сохранить',
    cancel: 'Отмена',
    language: 'Язык',
    uploadAvatar: 'Загрузить аватар',
    warnings: 'Предупреждения',
    memberSince: 'Участник с',
    loading: 'Загрузка...',
    errorLoading: 'Ошибка загрузки',
    back: 'Назад',
    startTest: 'Начать тест',
    submitTest: 'Отправить',
    nextQuestion: 'Далее',
    prevQuestion: 'Назад',
    timeLeft: 'Осталось',
    question: 'Вопрос',
    of: 'из',
    comments: 'Комментарии',
    addComment: 'Добавить комментарий',
    writeComment: 'Напишите комментарий...',
    send: 'Отправить',
    reply: 'Ответить',
    commentsDisabled: 'Комментарии отключены',
    deleteComment: 'Удалить',
    adminPanel: 'Панель администратора',
    users: 'Пользователи',
    tests: 'Тесты',
    statistics: 'Статистика',
    ban: 'Заблокировать',
    unban: 'Разблокировать',
    warn: 'Предупредить',
    banned: 'Заблокирован',
    role: 'Роль',
    search: 'Поиск',
    totalUsers: 'Всего пользователей',
    totalTests: 'Всего тестов',
    totalResults: 'Всего результатов',
    bannedUsers: 'Заблокировано',
    changeRole: 'Изменить роль',
    banUser: 'Заблокировать пользователя',
    banReason: 'Причина блокировки',
    warnMessage: 'Сообщение предупреждения',
    recentUsers: 'Новые пользователи',
    recentTests: 'Новые тесты',
    testResults: 'Результаты теста',
    score: 'Баллы',
    passed: 'Сдано',
    failed: 'Не сдано',
    viewResults: 'Результаты',
    notifications: 'Уведомления',
    noNotifications: 'Нет уведомлений',
    markAllRead: 'Прочитать все',
    report: 'Пожаловаться',
    reportReason: 'Причина жалобы',
    reportSent: 'Жалоба отправлена',
    reportTest: 'Пожаловаться на тест',
    reportComment: 'Пожаловаться на комментарий',
    reportUser: 'Пожаловаться на пользователя',
    editComment: 'Редактировать',
    cancelEditConfirm: 'Отменить изменения?',
    edited: 'изменено',
    testCreator: 'Автор',
    userProfile: 'Профиль пользователя',
    testsCreated: 'Тестов создано',
    testsTaken: 'Тестов пройдено',
    exportCSV: 'CSV',
    exportJSON: 'JSON',
    exportPDF: 'PDF',
    draftFound: 'Найден черновик',
    restoreDraft: 'Восстановить черновик?',
    restore: 'Восстановить',
    discard: 'Удалить',
    instantFeedback: 'Мгновенная проверка',
    instantFeedbackDesc: 'Показывает правильный ответ сразу после ответа',
    correct: 'Правильно',
    incorrect: 'Неправильно',
    checkAnswer: 'Проверить ответ',
    explanation: 'Пояснение',
    // Passage
    addPassage: 'Добавить текст для чтения',
    hidePassage: 'Скрыть текст',
    passage: 'Текст для чтения',
    passagePlaceholder: 'Введите текст/отрывок, который будет показан над вопросом...',
    passageLabel: 'Текст',
    // Question types
    singleChoice: 'Один ответ',
    multipleChoice: 'Несколько ответов',
    trueFalse: 'Верно / Неверно',
    essay: 'Эссе',
    matching: 'Сопоставление',
    fillBlank: 'Заполнить пропуск',
    // True-false options
    optTrue: 'Верно',
    optFalse: 'Неверно',
    optNotSure: 'Не уверен в ответе',
    // CreateTest
    minOneQuestion: 'Минимум 1 вопрос',
    enterTestTitle: 'Введите название теста',
    fillAllQuestions: 'Заполните все вопросы',
    testUpdated: 'Тест обновлён!',
    testCreated: 'Тест создан!',
    errorSaving: 'Ошибка сохранения',
    mediaUploaded: 'Медиа загружено',
    errorUploadMedia: 'Ошибка загрузки медиа',
    importedQuestions: 'Импортировано вопросов',
    cannotParseQuestions: 'Не удалось распознать вопросы. Проверьте формат.',
    errorReadingFile: 'Ошибка чтения файла',
    errorLoadingBank: 'Ошибка загрузки банка',
    addedFromBank: 'Добавлено вопросов из банка',
    savedToBank: 'Вопросы сохранены в банк',
    errorSavingToBank: 'Ошибка сохранения в банк',
    deleteQuestion: 'Удалить вопрос',
    deleteQuestionConfirm: 'Удалить вопрос №{{num}}? Это действие нельзя отменить.',
    navigation: 'Навигация',
    questionsCount: 'Вопросов',
    pointsCount: 'Баллов',
    fromQuestionBank: 'Из банка вопросов',
    importCSV: 'Импорт CSV',
    saveToBank: 'Сохранить в банк',
    aiGenerate: 'AI Генерация',
    aiGenerateDesc: 'Создать вопросы из текста или картинки',
    aiTextInput: 'Текстовый контент',
    aiTextPlaceholder: 'Вставьте текст, конспект, или любой материал для генерации вопросов...',
    aiImageInput: 'Картинка (скриншот, страница учебника)',
    aiUploadImage: 'Загрузить картинку',
    aiQuestionCount: 'Кол-во вопросов',
    aiQuestionTypes: 'Типы вопросов',
    aiGenerateBtn: 'Сгенерировать',
    aiGenerating: 'Генерация...',
    aiPoweredBy: 'Azure OpenAI',
    aiProvideContent: 'Введите текст или загрузите картинку',
    aiNoQuestions: 'AI не вернул вопросы. Попробуйте еще раз.',
    aiFileTooLarge: 'Файл слишком большой (макс 10МБ)',
    aiQuestionsAdded: '{{count}} вопросов добавлено!',
    editTest: 'Редактировать тест',
    settings: 'Настройки',
    update: 'Обновить',
    testSettings: 'Настройки теста',
    timeLimitMin: 'Время теста (мин)',
    maxAttempts: 'Макс. попыток',
    maxViolations: 'Макс. нарушений',
    isPublic: 'Публичный',
    shuffleQuestions: 'Перемешать вопросы',
    shuffleOptions: 'Перемешать ответы',
    showResults: 'Показать результаты',
    blockTabSwitch: 'Блок. вкладки',
    blockCopyPaste: 'Блок. копирование',
    blockScreenshot: 'Блок. скриншоты',
    testTitlePlaceholder: 'Название теста...',
    testDescPlaceholder: 'Описание теста (необязательно)...',
    newQuestion: 'Новый вопрос...',
    questionTextPlaceholder: 'Текст вопроса...',
    addMedia: 'Добавить медиа (фото, видео, аудио)',
    optionPlaceholder: 'Вариант',
    addOption: 'Добавить вариант',
    essayHint: 'Студент напишет развёрнутый ответ. Проверка преподавателем вручную.',
    correctAnswer: 'Правильный ответ',
    enterCorrectAnswer: 'Введите правильный ответ',
    element: 'Элемент',
    pair: 'Пара',
    addPair: 'Добавить пару',
    explanationPlaceholder: 'Пояснение к ответу (необязательно)...',
    addQuestion: 'Добавить вопрос',
    updateTest: 'Обновить тест',
    saveTest: 'Сохранить тест',
    importFromCSV: 'Импорт из CSV',
    clickToSelectFile: 'Нажмите, чтобы выбрать файл',
    questionBankTitle: 'Банк вопросов',
    bankEmpty: 'Банк пуст. Сохраните вопросы из теста, чтобы они появились здесь.',
    selectQuestions: 'Выберите вопросы',
    addSelected: 'Добавить выбранные',
    close: 'Закрыть',
    points: 'баллов',
    savingDraft: 'Сохранение...',
    draftSaved: 'Черновик сохранён',
    noLimitPlaceholder: '0 = без лимита',
    startDate: 'Дата начала',
    endDate: 'Дата окончания',
    questionPoolSize: 'Вопросов из пула',
    poolSizeHint: '0 = все вопросы',
    inactivityTimeout: 'Таймаут неактивности (мин)',
    inactivityHint: '0 = выключено',
    practiceMode: 'Режим тренировки',
    practiceModeDesc: 'Тренировка — безлимитные попытки, результаты не сохраняются',
    practiceModeLabel: 'Тренировка',
    partialCredit: 'Частичные баллы',
    partialCreditDesc: 'Начислять частичные баллы за частично правильные ответы (множественный выбор/сопоставление)',
    changeTicket: 'Сменить билет',
    ticketHintPublic: 'Выберите любой билет. Каждый билет доступен для всех.',
    aiHistory: 'История',
    aiNoHistory: 'История генераций пуста',
    clearAll: 'Очистить всё',
    exportJSON: 'Экспорт JSON',
    importJSON: 'Импорт JSON',
    exportSuccess: 'Тест экспортирован!',
    importSuccess: 'Тест импортирован!',
    importError: 'Ошибка импорта — некорректный файл',
    preview: 'Превью',
    previewMode: 'Режим предпросмотра — результат не сохранён',
    inactivityWarning: 'Вы ещё здесь?',
    inactivityCountdownMsg: 'Тест автоматически завершится через {{seconds}} сек',
    imHere: 'Я здесь!',
    category: 'Категория',
    allCategories: 'Все категории',
    // Ticket system
    ticketN: 'Билет #{{n}}',
    chooseTicket: 'Выберите билет',
    ticketReady: 'Билет закреплён за вами. Нажмите Начать!',
    claimingTicket: 'Выбираем билет...',
    ticketHint: 'Зелёный — свободен, Красный — занят. Выбирайте быстрее!',
    variantsEnabled: 'Система билетов/вариантов',
    variantCount: 'Количество вариантов',
    variantsHint: 'Каждый ученик получает уникальный билет с перемешанными вопросами',
    // TakeTest
    matchingHint: 'Нажмите на элемент слева, затем на его пару справа. Совпавшие пары будут выделены одним цветом.',
    elements: 'Элементы',
    pairs: 'Пары',
    yourPairs: 'Ваши пары:',
    violationLimitExceeded: 'Превышен лимит нарушений! Тест автоматически завершён.',
    timeUp: 'Время вышло!',
    testNotFound: 'Тест не найден',
    enterYourName: 'Введите ваше имя',
    errorCheckingAnswer: 'Ошибка проверки ответа',
    errorSubmitting: 'Ошибка отправки',
    point: 'балл',
    multipleAnswersHint: 'Можно выбрать несколько вариантов',
    checking: 'Проверяю...',
    writeYourAnswer: 'Напишите ваш ответ...',
    essayCheckedByTeacher: 'Эссе проверяется преподавателем после завершения',
    enterAnswer: 'Введите ответ...',
    correctAnswerIs: 'Правильный ответ',
    explanationLabel: 'Пояснение:',
    correctBanner: 'Правильно!',
    incorrectBanner: 'Неправильно',
    outOfPoints: 'из',
    finishTest: 'Завершить',
    finishTestTitle: 'Завершить тест',
    finishTestMessage: 'Вы ответили на {{answered}} из {{total}} вопросов. Завершить тест и отправить ответы?',
    finishBtn: 'Завершить',
    continueTest: 'Продолжить тест',
    startTestBtn: 'Начать тест',
    yourName: 'Ваше имя',
    enterFullName: 'Введите ваше полное имя',
    attempts: 'Попытки',
    allAttemptsUsed: 'Все попытки использованы',
    testRules: 'Правила прохождения теста:',
    ruleNoLeave: 'Нельзя покидать страницу теста (переключать вкладки, сворачивать браузер)',
    ruleViolationsTracked: 'Каждое нарушение фиксируется и видно преподавателю',
    ruleMaxViolations: 'Максимум нарушений: {{max}} — после этого тест завершится автоматически',
    modeInstantFeedback: 'Режим: Мгновенная проверка',
    instantFeedbackInfo: 'После каждого ответа вы сразу увидите, правильный ли он. Изменить ответ после проверки нельзя.',
    answered: 'отвечено',
    selectOption: 'выбрать',
    navigation: 'навигация',
    violation: 'Нарушение!',
    violationCount: 'Нарушение {{current}} из {{max}}',
    understood: 'Понятно',
    next: 'Далее',
    prev: 'Назад',
    // TestProfile
    questionTypes: 'Типы вопросов',
    rateTest: 'Оцените тест',
    yourRating: 'Ваша оценка',
    clickToRate: 'Нажмите для оценки',
    loginToRate: 'Войдите, чтобы оценить тест',
    ratingUpdated: 'Оценка обновлена',
    thanksForRating: 'Спасибо за оценку!',
    tabSwitchBlocked: 'Переключение вкладок запрещено. Макс. нарушений',
    allAttemptsUsedFull: 'Вы уже использовали все попытки',
    viewAll: 'Все →',
    min: 'мин',
    // Validation
    noCorrectAnswer: 'Вопрос {{num}}: отметьте правильный ответ',
    emptyOptions: 'Вопрос {{num}}: заполните все варианты ответов',
    // Dashboard
    errorLoadingTests: 'Ошибка загрузки тестов',
    testDeleted: 'Тест удалён',
    errorDeleting: 'Ошибка удаления',
    deleteTestTitle: 'Удалить тест',
    deleteTestMsg: 'Удалить этот тест? Все результаты также будут удалены.',
  },
  kz: {
    landingBadge: 'Білімді тексерудің ең оңай жолы',
    landingHeroTitle: 'Сеніммен бағалаңыз,',
    landingHeroSubtitle: 'Жасанды Интеллект көмегімен',
    landingHeroDesc: 'UniTest — оқытушыларға тест құруға, студенттерді бақылауға және нәтижелерді талдауға арналған кешенді платформа.',
    landingStartBtn: 'Тегін бастау',
    landingLoginBtn: 'Кіру',
    landingFeaturesHeader: 'Табысқа жету үшін қажеттінің бәрі',
    landingFeaturesSubHeader: 'Қазіргі заманғы оқытушылар мен оқу орындарына арналған қуатты құралдар.',
    landingFeatureAIGenTitle: 'ЖИ генерациясы',
    landingFeatureAIGenDesc: 'ЖИ көмегімен мәтіннен немесе құжаттардан көзді ашып жұмғанша сұрақтар жасаңыз.',
    landingFeatureLevelsTitle: 'Қиындық ДНҚ-сы',
    landingFeatureLevelsDesc: 'Білімді дәл бағалау үшін динамикалық 5 деңгейлі қиындық жүйесі.',
    landingFeatureAnalyticsTitle: 'Терең аналитика',
    landingFeatureAnalyticsDesc: 'Нақты уақыттағы аналитика мен егжей-тегжейлі есептер арқылы үлгерімді бақылаңыз.',
    landingFeatureSecurityTitle: 'Античит',
    landingFeatureSecurityDesc: 'Әділ тестілеу үшін браузерді бұғаттау, қойындыларды бақылау және қауіпсіз тексеру.',
    landingStepsHeader: 'Қалай жұмыс істейді',
    landingStepsSubHeader: 'Алғашқы тестіңізді жасап, нәтижелерді бірнеше минутта алыңыз.',
    landingStep1Title: 'Құру',
    landingStep1Desc: 'Тест сұрақтарын бірнеше секундта жазыңыз немесе генерациялаңыз.',
    landingStep2Title: 'Бөлісу',
    landingStep2Desc: 'Студенттерге немесе топтарға қысқа сілтеме жіберіңіз.',
    landingStep3Title: 'Талдау',
    landingStep3Desc: 'Нәтижелерді қарап, автоматты түрде бағалаңыз.',
    landingCtaHeader: 'Оқыту әдісін өзгертуге дайынсыз ба?',
    landingCtaDesc: 'UniTest-ті қазірдің өзінде пайдаланып жүрген мыңдаған оқытушыларға қосылыңыз.',
    landingCtaBtn: 'Тегін аккаунт құру',

    home: 'Басты',
    myTests: 'Менің тесттерім',
    results: 'Нәтижелер',
    questionBank: 'Сұрақ банкі',
    groups: 'Топтар',
    createTest: 'Тест құру',
    profile: 'Профиль',
    admin: 'Админ',
    logout: 'Шығу',
    teacher: 'Оқытушы',
    student: 'Студент',
    adminRole: 'Админ',
    lightTheme: 'Жарық тақырып',
    darkTheme: 'Қараңғы тақырып',
    welcome: 'Қош келдіңіз',
    dashboardSubtitle: 'Білімге қол жеткізіңіз және нәтижелерді қадағалаңыз',
    searchTests: 'Тесттерді іздеу...',
    newest: 'Жаңа',
    popular: 'Танымал',
    rating: 'Рейтинг',
    noTests: 'Тесттер жоқ',
    createFirst: 'Бірінші тестіңізді қазір жасаңыз',
    publicTest: 'Жалпыға қолжетімді',
    privateTest: 'Жеке',
    questions: 'сұрақ',
    noDescription: 'Сипаттама жоқ',
    deleteTest: 'Тестті жою',
    deleteTestConfirm: 'Бұл тестті жоюды қалайсыз ба? Барлық нәтижелер де жойылады.',
    delete: 'Жою',
    edit: 'Өңдеу',
    copyLink: 'Көшіру',
    linkCopied: 'Сілтеме көшірілді!',
    leaderboard: 'Рейтинг',
    totalParticipants: 'Барлық қатысушылар',
    emptyLeaderboard: 'Әзірге бос',
    noOneCompleted: 'Бұл тестті әлі ешкім тапсырмаған',
    error: 'Қате',
    toHome: 'Басты бетке',
    login: 'Кіру',
    register: 'Тіркелу',
    email: 'Email',
    password: 'Құпия сөз',
    firstName: 'Аты',
    lastName: 'Тегі',
    middleName: 'Әкесінің аты',
    noAccount: 'Аккаунтыңыз жоқ па?',
    haveAccount: 'Аккаунтыңыз бар ма?',
    loginBtn: 'Кіру',
    registerBtn: 'Тіркелу',
    profileTitle: 'Профиль',
    editProfile: 'Профильді өңдеу',
    changePassword: 'Құпия сөзді өзгерту',
    currentPassword: 'Ағымдағы құпия сөз',
    newPassword: 'Жаңа құпия сөз',
    save: 'Сақтау',
    cancel: 'Бас тарту',
    language: 'Тіл',
    uploadAvatar: 'Аватар жүктеу',
    warnings: 'Ескертулер',
    memberSince: 'Мүше болған уақыт',
    loading: 'Жүктелуде...',
    errorLoading: 'Жүктеу қатесі',
    back: 'Артқа',
    startTest: 'Тестті бастау',
    submitTest: 'Жіберу',
    nextQuestion: 'Келесі',
    prevQuestion: 'Алдыңғы',
    timeLeft: 'Қалған уақыт',
    question: 'Сұрақ',
    of: '/',
    comments: 'Пікірлер',
    addComment: 'Пікір қосу',
    writeComment: 'Пікір жазыңыз...',
    send: 'Жіберу',
    reply: 'Жауап беру',
    commentsDisabled: 'Пікірлер өшірілген',
    deleteComment: 'Жою',
    adminPanel: 'Әкімші панелі',
    users: 'Пайдаланушылар',
    tests: 'Тесттер',
    statistics: 'Статистика',
    ban: 'Бұғаттау',
    unban: 'Бұғатты алу',
    warn: 'Ескерту',
    banned: 'Бұғатталған',
    role: 'Рөл',
    search: 'Іздеу',
    totalUsers: 'Барлық пайдаланушылар',
    totalTests: 'Барлық тесттер',
    totalResults: 'Барлық нәтижелер',
    bannedUsers: 'Бұғатталған',
    changeRole: 'Рөлді өзгерту',
    banUser: 'Пайдаланушыны бұғаттау',
    banReason: 'Бұғаттау себебі',
    warnMessage: 'Ескерту хабарламасы',
    recentUsers: 'Жаңа пайдаланушылар',
    recentTests: 'Жаңа тесттер',
    testResults: 'Тест нәтижелері',
    score: 'Ұпай',
    passed: 'Тапсырылды',
    failed: 'Тапсырылмады',
    viewResults: 'Нәтижелер',
    notifications: 'Хабарламалар',
    noNotifications: 'Хабарламалар жоқ',
    markAllRead: 'Барлығын оқылды деп белгілеу',
    report: 'Шағым',
    reportReason: 'Шағым себебі',
    reportSent: 'Шағым жіберілді',
    reportTest: 'Тестке шағымдану',
    reportComment: 'Пікірге шағымдану',
    reportUser: 'Пайдаланушыға шағымдану',
    editComment: 'Өңдеу',
    cancelEditConfirm: 'Өзгерістерді болдырмау керек пе?',
    edited: 'өңделген',
    testCreator: 'Автор',
    userProfile: 'Пайдаланушы профилі',
    testsCreated: 'Жасалған тесттер',
    testsTaken: 'Тапсырылған тесттер',
    exportCSV: 'CSV',
    exportJSON: 'JSON',
    exportPDF: 'PDF',
    draftFound: 'Жоба табылды',
    restoreDraft: 'Жобаны қалпына келтіру?',
    restore: 'Қалпына келтіру',
    discard: 'Жою',
    instantFeedback: 'Лездік тексеру',
    instantFeedbackDesc: 'Жауап бергеннен кейін дұрыс жауапты көрсетеді',
    correct: 'Дұрыс',
    incorrect: 'Қате',
    checkAnswer: 'Жауапты тексеру',
    explanation: 'Түсіндірме',
    // Passage
    addPassage: 'Оқу мәтінін қосу',
    hidePassage: 'Мәтінді жасыру',
    passage: 'Оқу мәтіні',
    passagePlaceholder: 'Сұрақтың үстінде көрсетілетін мәтін/үзіндіні енгізіңіз...',
    passageLabel: 'Мәтін',
    // Question types
    singleChoice: 'Бір жауап',
    multipleChoice: 'Бірнеше жауап',
    trueFalse: 'Дұрыс / Бұрыс',
    essay: 'Эссе',
    matching: 'Сәйкестендіру',
    fillBlank: 'Бос орынды толтыру',
    // True-false options
    optTrue: 'Дұрыс',
    optFalse: 'Бұрыс',
    optNotSure: 'Жауапқа сенімді емеспін',
    // CreateTest
    minOneQuestion: 'Кемінде 1 сұрақ',
    enterTestTitle: 'Тест атауын енгізіңіз',
    fillAllQuestions: 'Барлық сұрақтарды толтырыңыз',
    testUpdated: 'Тест жаңартылды!',
    testCreated: 'Тест құрылды!',
    errorSaving: 'Сақтау қатесі',
    mediaUploaded: 'Медиа жүктелді',
    errorUploadMedia: 'Медиа жүктеу қатесі',
    importedQuestions: 'Импортталған сұрақтар',
    cannotParseQuestions: 'Сұрақтарды тану мүмкін болмады. Форматты тексеріңіз.',
    errorReadingFile: 'Файлды оқу қатесі',
    errorLoadingBank: 'Банкті жүктеу қатесі',
    addedFromBank: 'Банктан сұрақтар қосылды',
    savedToBank: 'Сұрақтар банкке сақталды',
    errorSavingToBank: 'Банкке сақтау қатесі',
    deleteQuestion: 'Сұрақты жою',
    deleteQuestionConfirm: '{{num}} сұрақты жою? Бұл әрекетті қайтару мүмкін емес.',
    navigation: 'Навигация',
    questionsCount: 'Сұрақтар',
    pointsCount: 'Ұпайлар',
    fromQuestionBank: 'Сұрақ банкінен',
    importCSV: 'CSV импорт',
    saveToBank: 'Банкке сақтау',
    aiGenerate: 'AI Генерация',
    aiGenerateDesc: 'Мәтін немесе суреттен сұрақтар құру',
    aiTextInput: 'Мәтін',
    aiTextPlaceholder: 'Мәтін, конспект немесе кез-келген материалды қойыңыз...',
    aiImageInput: 'Сурет (скриншот, оқулық беті)',
    aiUploadImage: 'Сурет жүктеу',
    aiQuestionCount: 'Сұрақ саны',
    aiQuestionTypes: 'Сұрақ түрлері',
    aiGenerateBtn: 'Генерациялау',
    aiGenerating: 'Генерация...',
    aiPoweredBy: 'Azure OpenAI',
    aiProvideContent: 'Мәтін енгізіңіз немесе сурет жүктеңіз',
    aiNoQuestions: 'AI сұрақтар қайтармады. Қайта көріңіз.',
    aiFileTooLarge: 'Файл тым үлкен (макс 10МБ)',
    aiQuestionsAdded: '{{count}} сұрақ қосылды!',
    editTest: 'Тестті өңдеу',
    settings: 'Баптаулар',
    update: 'Жаңарту',
    testSettings: 'Тест баптаулары',
    timeLimitMin: 'Уақыт шегі (мин)',
    maxAttempts: 'Макс. әрекеттер',
    maxViolations: 'Макс. бұзушылықтар',
    isPublic: 'Жалпыға қолжетімді',
    shuffleQuestions: 'Сұрақтарды араластыру',
    shuffleOptions: 'Жауаптарды араластыру',
    showResults: 'Нәтижелерді көрсету',
    blockTabSwitch: 'Қойындыларды блоктау',
    blockCopyPaste: 'Көшіруді блоктау',
    blockScreenshot: 'Скриншотты блоктау',
    testTitlePlaceholder: 'Тест атауы...',
    testDescPlaceholder: 'Тест сипаттамасы (міндетті емес)...',
    newQuestion: 'Жаңа сұрақ...',
    questionTextPlaceholder: 'Сұрақ мәтіні...',
    addMedia: 'Медиа қосу (фото, видео, аудио)',
    optionPlaceholder: 'Нұсқа',
    addOption: 'Нұсқа қосу',
    essayHint: 'Студент толық жауап жазады. Оқытушы қолмен тексереді.',
    correctAnswer: 'Дұрыс жауап',
    enterCorrectAnswer: 'Дұрыс жауапты енгізіңіз',
    element: 'Элемент',
    pair: 'Жұп',
    addPair: 'Жұп қосу',
    explanationPlaceholder: 'Жауапқа түсіндірме (міндетті емес)...',
    addQuestion: 'Сұрақ қосу',
    updateTest: 'Тестті жаңарту',
    saveTest: 'Тестті сақтау',
    importFromCSV: 'CSV-ден импорт',
    clickToSelectFile: 'Файлды таңдау үшін басыңыз',
    questionBankTitle: 'Сұрақ банкі',
    bankEmpty: 'Банк бос. Мұнда көріну үшін тесттен сұрақтарды сақтаңыз.',
    selectQuestions: 'Сұрақтарды таңдаңыз',
    addSelected: 'Таңдалғандарды қосу',
    close: 'Жабу',
    points: 'ұпай',
    savingDraft: 'Сақтау...',
    draftSaved: 'Жоба сақталды',
    noLimitPlaceholder: '0 = шексіз',
    startDate: 'Басталу күні',
    endDate: 'Аяқталу күні',
    questionPoolSize: 'Пулдан сұрақтар',
    poolSizeHint: '0 = барлық сұрақтар',
    inactivityTimeout: 'Белсенділік тоқтау (мин)',
    inactivityHint: '0 = өшірілген',
    practiceMode: 'Жаттығу режимі',
    practiceModeDesc: 'Жаттығу — шексіз әрекеттер, нәтижелер сақталмайды',
    practiceModeLabel: 'Жаттығу',
    partialCredit: 'Жартылай балл',
    partialCreditDesc: 'Жартылай дұрыс жауаптар үшін жартылай балл беру (көп таңдау/сәйкестендіру)',
    changeTicket: 'Билетті ауыстыру',
    ticketHintPublic: 'Кез келген билетті таңдаңыз. Барлық билеттер барлығына қолжетімді.',
    aiHistory: 'Тарих',
    aiNoHistory: 'Генерация тарихы бос',
    clearAll: 'Барлығын тазалау',
    exportJSON: 'JSON экспорт',
    importJSON: 'JSON импорт',
    exportSuccess: 'Тест экспортталды!',
    importSuccess: 'Тест импортталды!',
    importError: 'Импорт қатесі — файл дұрыс емес',
    preview: 'Алдын ала қарау',
    previewMode: 'Алдын ала қарау — нәтиже сақталмайды',
    inactivityWarning: 'Сіз әлі мұндасыз ба?',
    inactivityCountdownMsg: 'Тест {{seconds}} сек ішінде автоматты аяқталады',
    imHere: 'Мен мұндамын!',
    category: 'Санат',
    allCategories: 'Барлық санаттар',
    // Ticket system
    ticketN: 'Билет #{{n}}',
    chooseTicket: 'Билетті таңдаңыз',
    ticketReady: 'Билет сіздікі. Бастау батырмасын басыңыз!',
    claimingTicket: 'Билет таңдалуда...',
    ticketHint: 'Жасыл — бос, Қызыл — бос емес. Тезірек таңдаңыз!',
    variantsEnabled: 'Билет/вариант жүйесі',
    variantCount: 'Вариант саны',
    variantsHint: 'Әр оқушы бірегей билет алады, сұрақтар аралас болады',
    // TakeTest
    matchingHint: 'Сол жақтағы элементті, содан кейін оң жақтағы жұбын басыңыз. Сәйкес жұптар бірдей түспен ерекшеленеді.',
    elements: 'Элементтер',
    pairs: 'Жұптар',
    yourPairs: 'Сіздің жұптарыңыз:',
    violationLimitExceeded: 'Бұзушылық шегі асылды! Тест автоматты түрде аяқталды.',
    timeUp: 'Уақыт бітті!',
    testNotFound: 'Тест табылмады',
    enterYourName: 'Атыңызды енгізіңіз',
    errorCheckingAnswer: 'Жауапты тексеру қатесі',
    errorSubmitting: 'Жіберу қатесі',
    point: 'ұпай',
    multipleAnswersHint: 'Бірнеше нұсқаны таңдауға болады',
    checking: 'Тексеруде...',
    writeYourAnswer: 'Жауабыңызды жазыңыз...',
    essayCheckedByTeacher: 'Эссе аяқтағаннан кейін оқытушы тексереді',
    enterAnswer: 'Жауабыңызды енгізіңіз...',
    correctAnswerIs: 'Дұрыс жауап',
    explanationLabel: 'Түсіндірме:',
    correctBanner: 'Дұрыс!',
    incorrectBanner: 'Қате',
    outOfPoints: '/',
    finishTest: 'Аяқтау',
    finishTestTitle: 'Тестті аяқтау',
    finishTestMessage: 'Сіз {{total}} сұрақтың {{answered}} жауап бердіңіз. Тестті аяқтап, жауаптарды жіберу керек пе?',
    finishBtn: 'Аяқтау',
    continueTest: 'Тестті жалғастыру',
    startTestBtn: 'Тестті бастау',
    yourName: 'Сіздің атыңыз',
    enterFullName: 'Толық атыңызды енгізіңіз',
    attempts: 'Әрекеттер',
    allAttemptsUsed: 'Барлық әрекеттер пайдаланылды',
    testRules: 'Тест ережелері:',
    ruleNoLeave: 'Тест бетінен шығуға болмайды (қойындыларды ауыстыру, браузерді кішірейту)',
    ruleViolationsTracked: 'Әр бұзушылық тіркеледі және оқытушыға көрінеді',
    ruleMaxViolations: 'Максимум бұзушылықтар: {{max}} — содан кейін тест автоматты түрде аяқталады',
    modeInstantFeedback: 'Режим: Лездік тексеру',
    instantFeedbackInfo: 'Әр жауаптан кейін оның дұрыс екенін бірден көресіз. Тексергеннен кейін жауапты өзгертуге болмайды.',
    answered: 'жауап берілді',
    selectOption: 'тандау',
    navigation: 'навигация',
    violation: 'Бұзушылық!',
    violationCount: 'Бұзушылық {{current}} / {{max}}',
    understood: 'Түсінікті',
    next: 'Келесі',
    prev: 'Артқа',
    // TestProfile
    questionTypes: 'Сұрақ түрлері',
    rateTest: 'Тестті бағалаңыз',
    yourRating: 'Сіздің бағаңыз',
    clickToRate: 'Бағалау үшін басыңыз',
    loginToRate: 'Тестті бағалау үшін кіріңіз',
    ratingUpdated: 'Баға жаңартылды',
    thanksForRating: 'Бағалағаныңыз үшін рахмет!',
    tabSwitchBlocked: 'Қойындыларды ауыстыру тыйым салынған. Макс. бұзушылықтар',
    allAttemptsUsedFull: 'Сіз барлық әрекеттерді пайдаландыңыз',
    viewAll: 'Барлығы →',
    min: 'мин',
    // Validation
    noCorrectAnswer: '{{num}} сұрақ: дұрыс жауапты белгілеңіз',
    emptyOptions: '{{num}} сұрақ: барлық жауап нұсқаларын толтырыңыз',
    // Dashboard
    errorLoadingTests: 'Тесттерді жүктеу қатесі',
    testDeleted: 'Тест жойылды',
    errorDeleting: 'Жою қатесі',
    deleteTestTitle: 'Тестті жою',
    deleteTestMsg: 'Бұл тестті жоюды қалайсыз ба? Барлық нәтижелер де жойылады.',
  }
};

Object.assign(translations.en, {
  optNotSure: 'Not given',
  multiLanguage: 'Multilingual',
  multiLanguageEnabled: 'Enable translations',
  multiLanguageHint: 'Select the languages that should be available during the test.',
  translations: 'Translations',
  securityLabel: 'Security',
  original: 'Original',
  uploadCover: 'Upload cover',
  coverImage: 'Test cover',
  aiQuestionMix: 'Question mix',
  aiQuestionMixDesc: 'Choose exactly how many questions of each type to generate.',
  aiDifficulty: 'Difficulty',
  aiDifficultyHint: 'The AI will target this overall difficulty when generating questions.',
  aiTotalQuestions: 'Total questions',
  aiUseAtLeastOneType: 'Select at least one question type',
  difficultyVeryEasy: 'Very easy',
  difficultyEasy: 'Easy',
  difficultyMedium: 'Medium',
  difficultyHard: 'Hard',
  difficultyExpert: 'Expert',
  ticketChosen: 'Ticket {{n}} selected!',
  ticketAlreadyTaken: 'This ticket is already taken!',
  ticketSelectError: 'Failed to select the ticket',
  testNotAvailableYet: 'Test is not available yet',
  testFinished: 'Test is finished',
  testOpensAt: 'The test opens at: {{date}}',
  testWasAvailableUntil: 'The test was available until: {{date}}',
  partialCreditLabel: 'partial credit',
  profileLoadError: 'Failed to load profile data',
  profileNameRequired: 'First name and last name are required',
  passwordFieldsRequired: 'Please fill in all password fields',
  passwordsMismatch: 'New passwords do not match',
  passwordMinLength: 'The new password must be at least 6 characters',
  copied: 'Copied!',
  commentDeleted: 'Comment deleted',
  deleteError: 'Deletion error',
  avgScore: 'Average score',
  repeatNewPassword: 'Repeat new password',
  noCommentsYet: 'No comments yet',
  leaveTestAutoSubmit: 'You tried to leave the test. Your attempt is being submitted automatically.',
  warningsEmptyTitle: 'No warnings',
  warningsEmptyDesc: 'Messages from administrators will appear here.'
});

Object.assign(translations.ru, {
  optNotSure: 'Не указано',
  multiLanguage: 'Мультиязычность',
  multiLanguageEnabled: 'Включить переводы',
  multiLanguageHint: 'Выберите языки, которые будут доступны во время теста.',
  translations: 'Переводы',
  securityLabel: 'Безопасность',
  original: 'Оригинал',
  uploadCover: 'Загрузить обложку',
  coverImage: 'Обложка теста',
  aiQuestionMix: 'Состав вопросов',
  aiQuestionMixDesc: 'Укажите точное количество вопросов каждого типа.',
  aiDifficulty: 'Сложность',
  aiDifficultyHint: 'ИИ будет ориентироваться на этот общий уровень сложности.',
  aiTotalQuestions: 'Всего вопросов',
  aiUseAtLeastOneType: 'Выберите хотя бы один тип вопроса',
  difficultyVeryEasy: 'Очень легко',
  difficultyEasy: 'Легко',
  difficultyMedium: 'Средне',
  difficultyHard: 'Сложно',
  difficultyExpert: 'Экспертно',
  ticketChosen: 'Билет #{{n}} выбран!',
  ticketAlreadyTaken: 'Этот билет уже занят!',
  ticketSelectError: 'Ошибка при выборе билета',
  testNotAvailableYet: 'Тест ещё не доступен',
  testFinished: 'Тест завершён',
  testOpensAt: 'Тест откроется: {{date}}',
  testWasAvailableUntil: 'Тест был доступен до: {{date}}',
  partialCreditLabel: 'частичный балл',
  profileLoadError: 'Не удалось загрузить данные профиля',
  profileNameRequired: 'Имя и фамилия обязательны к заполнению',
  passwordFieldsRequired: 'Пожалуйста, заполните все поля пароля',
  passwordsMismatch: 'Новые пароли не совпадают',
  passwordMinLength: 'Новый пароль должен быть минимум 6 символов',
  copied: 'Скопировано!',
  commentDeleted: 'Комментарий удалён',
  deleteError: 'Ошибка удаления',
  avgScore: 'Средний балл',
  repeatNewPassword: 'Повторите новый пароль',
  noCommentsYet: 'Комментариев пока нет',
  leaveTestAutoSubmit: 'Вы попытались покинуть тест. Попытка автоматически отправляется.',
  warningsEmptyTitle: 'Предупреждений нет',
  warningsEmptyDesc: 'Сообщения от администраторов будут появляться здесь.'
});

Object.assign(translations.kz, {
  optNotSure: 'Берілмеген',
  multiLanguage: 'Көптілділік',
  multiLanguageEnabled: 'Аудармаларды қосу',
  multiLanguageHint: 'Тест кезінде қолжетімді болатын тілдерді таңдаңыз.',
  translations: 'Аудармалар',
  securityLabel: 'Қауіпсіздік',
  original: 'Түпнұсқа',
  uploadCover: 'Мұқабаны жүктеу',
  coverImage: 'Тест мұқабасы',
  aiQuestionMix: 'Сұрақ құрамы',
  aiQuestionMixDesc: 'Әр типтен қанша сұрақ керек екенін дәл көрсетіңіз.',
  aiDifficulty: 'Күрделілік',
  aiDifficultyHint: 'AI осы жалпы күрделілік деңгейіне сүйеніп сұрақтар жасайды.',
  aiTotalQuestions: 'Барлық сұрақ',
  aiUseAtLeastOneType: 'Кемінде бір сұрақ түрін таңдаңыз',
  difficultyVeryEasy: 'Өте жеңіл',
  difficultyEasy: 'Жеңіл',
  difficultyMedium: 'Орташа',
  difficultyHard: 'Қиын',
  difficultyExpert: 'Сарапшы',
  ticketChosen: '{{n}} билет таңдалды!',
  ticketAlreadyTaken: 'Бұл билет бос емес!',
  ticketSelectError: 'Билетті таңдау қатесі',
  testNotAvailableYet: 'Тест әлі қолжетімді емес',
  testFinished: 'Тест аяқталды',
  testOpensAt: 'Тест ашылады: {{date}}',
  testWasAvailableUntil: 'Тест қолжетімді болған уақыт: {{date}}',
  partialCreditLabel: 'жартылай балл',
  profileLoadError: 'Профиль деректерін жүктеу мүмкін болмады',
  profileNameRequired: 'Аты мен тегі міндетті',
  passwordFieldsRequired: 'Құпия сөз өрістерінің барлығын толтырыңыз',
  passwordsMismatch: 'Жаңа құпия сөздер сәйкес келмейді',
  passwordMinLength: 'Жаңа құпия сөз кемінде 6 таңба болуы керек',
  copied: 'Көшірілді!',
  commentDeleted: 'Пікір жойылды',
  deleteError: 'Жою қатесі',
  avgScore: 'Орташа ұпай',
  repeatNewPassword: 'Жаңа құпия сөзді қайталаңыз',
  noCommentsYet: 'Әзірге пікір жоқ',
  leaveTestAutoSubmit: 'Сіз тесттен шығуға әрекет жасадыңыз. Әрекет автоматты түрде жіберілуде.',
  warningsEmptyTitle: 'Ескерту жоқ',
  warningsEmptyDesc: 'Әкімшілердің хабарламалары осы жерде көрсетіледі.'
});

translations.es = {
  ...translations.en,
  landingBadge: 'La forma más sencilla de evaluar conocimientos',
  landingHeroTitle: 'Evalúa con confianza,',
  landingHeroSubtitle: 'impulsado por IA',
  landingHeroDesc: 'UniTest es una plataforma integral para docentes: crea exámenes, supervisa estudiantes y analiza resultados.',
  landingStartBtn: 'Empezar gratis',
  landingLoginBtn: 'Iniciar sesión',
  landingFeaturesHeader: 'Todo lo que necesitas para enseñar mejor',
  landingFeaturesSubHeader: 'Herramientas potentes creadas para docentes e instituciones modernas.',
  landingFeatureAIGenTitle: 'Generación con IA',
  landingFeatureAIGenDesc: 'Genera preguntas a partir de texto o documentos al instante.',
  landingFeatureLevelsTitle: 'ADN de dificultad',
  landingFeatureLevelsDesc: 'Sistema dinámico de 5 niveles para medir conocimientos con precisión.',
  landingFeatureAnalyticsTitle: 'Analítica profunda',
  landingFeatureAnalyticsDesc: 'Sigue el rendimiento con analítica en tiempo real e informes detallados.',
  landingFeatureSecurityTitle: 'Antitrampas',
  landingFeatureSecurityDesc: 'Bloqueo del navegador, seguimiento de pestañas y ejecución segura.',
  landingStepsHeader: 'Cómo funciona',
  landingStepsSubHeader: 'Crea tu primer examen y obtén resultados en minutos.',
  landingStep1Title: 'Crear',
  landingStep1Desc: 'Escribe o genera preguntas en segundos.',
  landingStep2Title: 'Compartir',
  landingStep2Desc: 'Envía un enlace corto a estudiantes o grupos.',
  landingStep3Title: 'Analizar',
  landingStep3Desc: 'Revisa resultados y califica automáticamente.',
  landingCtaHeader: '¿Listo para transformar tu enseñanza?',
  landingCtaDesc: 'Únete a miles de docentes que ya usan UniTest.',
  landingCtaBtn: 'Crear cuenta gratis',
  home: 'Inicio',
  myTests: 'Mis exámenes',
  results: 'Resultados',
  questionBank: 'Banco de preguntas',
  groups: 'Grupos',
  createTest: 'Crear examen',
  profile: 'Perfil',
  admin: 'Admin',
  logout: 'Cerrar sesión',
  teacher: 'Docente',
  student: 'Estudiante',
  adminRole: 'Administrador',
  lightTheme: 'Tema claro',
  darkTheme: 'Tema oscuro',
  welcome: 'Bienvenido',
  dashboardSubtitle: 'Accede al conocimiento y sigue tu progreso',
  searchTests: 'Buscar exámenes...',
  newest: 'Nuevos',
  popular: 'Populares',
  rating: 'Valoración',
  noTests: 'Aún no hay exámenes',
  createFirst: 'Crea tu primer examen ahora mismo',
  publicTest: 'Público',
  privateTest: 'Privado',
  questions: 'preguntas',
  noDescription: 'Sin descripción',
  delete: 'Eliminar',
  edit: 'Editar',
  copyLink: 'Copiar enlace',
  linkCopied: '¡Enlace copiado!',
  login: 'Iniciar sesión',
  register: 'Registrarse',
  email: 'Correo',
  password: 'Contraseña',
  firstName: 'Nombre',
  lastName: 'Apellido',
  middleName: 'Segundo nombre',
  noAccount: '¿No tienes cuenta?',
  haveAccount: '¿Ya tienes cuenta?',
  loginBtn: 'Entrar',
  registerBtn: 'Crear cuenta',
  profileTitle: 'Perfil',
  editProfile: 'Editar perfil',
  changePassword: 'Cambiar contraseña',
  currentPassword: 'Contraseña actual',
  newPassword: 'Nueva contraseña',
  save: 'Guardar',
  cancel: 'Cancelar',
  language: 'Idioma',
  uploadAvatar: 'Subir avatar',
  warnings: 'Advertencias',
  memberSince: 'Miembro desde',
  loading: 'Cargando...',
  errorLoading: 'Error al cargar',
  back: 'Atrás',
  comments: 'Comentarios',
  addComment: 'Añadir comentario',
  writeComment: 'Escribe un comentario...',
  send: 'Enviar',
  reply: 'Responder',
  singleChoice: 'Respuesta única',
  multipleChoice: 'Respuestas múltiples',
  trueFalse: 'Verdadero / Falso',
  essay: 'Ensayo',
  matching: 'Relacionar',
  fillBlank: 'Completar espacio',
  optTrue: 'Verdadero',
  optFalse: 'Falso',
  optNotSure: 'No se indica',
  aiGenerate: 'Generar con IA',
  aiGenerateDesc: 'Crea preguntas a partir de texto, archivos o imágenes',
  aiTextInput: 'Texto',
  aiTextPlaceholder: 'Pega texto, apuntes o cualquier material...',
  aiFileInput: 'Archivo (PDF, DOCX, TXT, imagen)',
  aiUploadFile: 'Subir PDF, DOCX, TXT o imagen',
  aiQuestionCount: 'Preguntas',
  aiQuestionTypes: 'Tipos de pregunta',
  aiGenerateBtn: 'Generar',
  aiGenerating: 'Generando...',
  aiProvideContent: 'Añade texto o sube un archivo',
  aiNoQuestions: 'La IA no devolvió preguntas. Inténtalo de nuevo.',
  aiFileTooLarge: 'Archivo demasiado grande (máx. 20 MB)',
  aiQuestionsAdded: '¡{{count}} preguntas añadidas!',
  aiHistory: 'Historial',
  aiNoHistory: 'Todavía no hay historial de generación',
  clearAll: 'Borrar todo',
  selectAll: 'Seleccionar todo',
  deselectAll: 'Deseleccionar todo',
  addQuestions: 'Añadir preguntas',
  regenerate: 'Regenerar',
  multiLanguage: 'Multilingüe',
  multiLanguageEnabled: 'Activar traducciones',
  multiLanguageHint: 'Selecciona los idiomas disponibles durante el examen.',
  translations: 'Traducciones',
  securityLabel: 'Seguridad',
  original: 'Original',
  uploadCover: 'Subir portada',
  coverImage: 'Portada del examen',
  aiQuestionMix: 'Distribución de preguntas',
  aiQuestionMixDesc: 'Elige cuántas preguntas generar de cada tipo.',
  aiDifficulty: 'Dificultad',
  aiDifficultyHint: 'La IA ajustará las preguntas a este nivel general.',
  aiTotalQuestions: 'Total de preguntas',
  aiUseAtLeastOneType: 'Selecciona al menos un tipo de pregunta',
  difficultyVeryEasy: 'Muy fácil',
  difficultyEasy: 'Fácil',
  difficultyMedium: 'Media',
  difficultyHard: 'Difícil',
  difficultyExpert: 'Experto',
  ticketChosen: '¡Boleto {{n}} seleccionado!',
  ticketAlreadyTaken: '¡Este boleto ya está ocupado!',
  ticketSelectError: 'Error al seleccionar el boleto',
  testNotAvailableYet: 'El examen aún no está disponible',
  testFinished: 'El examen ha terminado',
  testOpensAt: 'El examen se abrirá: {{date}}',
  testWasAvailableUntil: 'El examen estuvo disponible hasta: {{date}}',
  partialCreditLabel: 'crédito parcial',
  profileLoadError: 'No se pudieron cargar los datos del perfil',
  profileNameRequired: 'El nombre y el apellido son obligatorios',
  passwordFieldsRequired: 'Completa todos los campos de la contraseña',
  passwordsMismatch: 'Las nuevas contraseñas no coinciden',
  passwordMinLength: 'La nueva contraseña debe tener al menos 6 caracteres',
  copied: '¡Copiado!',
  commentDeleted: 'Comentario eliminado',
  deleteError: 'Error al eliminar',
  avgScore: 'Puntuación media',
  repeatNewPassword: 'Repite la nueva contraseña',
  noCommentsYet: 'Todavía no hay comentarios',
  testSettings: 'Configuración del examen',
  shuffleQuestions: 'Mezclar preguntas',
  shuffleOptions: 'Mezclar respuestas',
  showResults: 'Mostrar resultados',
  timeLimitMin: 'Límite de tiempo (min)',
  maxAttempts: 'Máximo de intentos',
  maxViolations: 'Máximo de infracciones',
  isPublic: 'Público',
  blockTabSwitch: 'Bloquear pestañas',
  blockCopyPaste: 'Bloquear copiar',
  blockScreenshot: 'Bloquear capturas',
  instantFeedback: 'Comprobación inmediata',
  instantFeedbackDesc: 'Muestra la respuesta correcta justo después de contestar',
  passageLabel: 'Texto',
  questionTextPlaceholder: 'Texto de la pregunta...',
  addOption: 'Añadir opción',
  correctAnswer: 'Respuesta correcta',
  enterCorrectAnswer: 'Introduce la respuesta correcta',
  addQuestion: 'Añadir pregunta',
  saveTest: 'Guardar examen',
  updateTest: 'Actualizar examen',
  testCreated: '¡Examen creado!',
  testUpdated: '¡Examen actualizado!',
  errorSaving: 'Error al guardar',
  startTestBtn: 'Empezar examen',
  yourName: 'Tu nombre',
  enterFullName: 'Introduce tu nombre completo',
  attempts: 'Intentos',
  allAttemptsUsed: 'Ya usaste todos los intentos',
  testRules: 'Reglas del examen:',
  ruleNoLeave: 'No puedes salir de la página del examen ni cambiar de pestaña',
  ruleViolationsTracked: 'Cada infracción se registra y es visible para el docente',
  ruleMaxViolations: 'Máximo de infracciones: {{max}}. Después, el examen termina automáticamente',
  modeInstantFeedback: 'Modo: comprobación inmediata',
  instantFeedbackInfo: 'Después de cada respuesta verás de inmediato si es correcta. No podrás cambiarla después de comprobarla.',
  violationLimitExceeded: '¡Se superó el límite de infracciones! El examen se envió automáticamente.',
  timeUp: '¡Se acabó el tiempo!',
  testNotFound: 'Examen no encontrado',
  enterYourName: 'Introduce tu nombre',
  errorCheckingAnswer: 'Error al comprobar la respuesta',
  errorSubmitting: 'Error al enviar',
  point: 'punto',
  points: 'puntos',
  multipleAnswersHint: 'Puedes seleccionar varias opciones',
  checking: 'Comprobando...',
  writeYourAnswer: 'Escribe tu respuesta...',
  essayCheckedByTeacher: 'El ensayo será revisado por el docente después del envío',
  enterAnswer: 'Introduce tu respuesta...',
  correctAnswerIs: 'Respuesta correcta',
  explanationLabel: 'Explicación:',
  correctBanner: '¡Correcto!',
  incorrectBanner: 'Incorrecto',
  outOfPoints: 'de',
  finishTest: 'Finalizar examen',
  finishTestTitle: 'Finalizar examen',
  finishTestMessage: 'Has respondido {{answered}} de {{total}} preguntas. ¿Quieres finalizar y enviar tus respuestas?',
  finishBtn: 'Finalizar',
  continueTest: 'Continuar examen',
  answered: 'respondidas',
  selectOption: 'seleccionar',
  navigation: 'navegar',
  violation: '¡Infracción!',
  violationCount: 'Infracción {{current}} de {{max}}',
  understood: 'Entendido',
  next: 'Siguiente',
  prev: 'Atrás',
  chooseTicket: 'Elige tu boleto',
  ticketReady: 'Tu boleto ya está fijado. Pulsa iniciar.',
  claimingTicket: 'Reservando boleto...',
  ticketHint: 'Verde: disponible. Rojo: ocupado.',
  changeTicket: 'Cambiar boleto',
  ticketHintPublic: 'Puedes elegir cualquier boleto. Todos están disponibles para todos.',
  practiceMode: 'Modo práctica',
  practiceModeDesc: 'Modo entrenamiento: intentos ilimitados y resultados no guardados',
  leaveTestAutoSubmit: 'Intentaste salir del examen. Tu intento se está enviando automáticamente.',
  warningsEmptyTitle: 'Sin advertencias',
  warningsEmptyDesc: 'Los mensajes de los administradores aparecerán aquí.'
};

const LanguageContext = createContext(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    const saved = localStorage.getItem('unitest_lang');
    if (saved && ['en', 'ru', 'kz', 'es'].includes(saved)) return saved;
    return 'en';
  });

  useEffect(() => {
    localStorage.setItem('unitest_lang', lang);
  }, [lang]);

  const t = useCallback((key, params) => {
    let text = translations[lang]?.[key] || translations.en[key] || key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(new RegExp(`\\{\\{${k}\\}\\}`, 'g'), v);
      });
    }
    return text;
  }, [lang]);

  const setLanguage = useCallback((newLang) => {
    if (['en', 'ru', 'kz', 'es'].includes(newLang)) {
      setLang(newLang);
    }
  }, []);

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
